/*
 * Copyright (c) 2016 SLIIT, All Rights Reserved.
 * HOME MANAGEMENT SYSTEM
 * SEP GROUP PROJECT - 3rd YEAR
 *
 */
package view.event;

import controller.event.EventController;
import model.event.EventPlan;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JSpinner;
import javax.swing.JSpinner.DateEditor;
import javax.swing.SpinnerDateModel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.event.Eventnbev;
import model.event.Eventncontact;
import model.event.Eventnfood;
import model.event.Eventnitems;

/**
 * AddEvent -- main Interface for Home Event Management 
 * @author Isurunath
 */
public class AddEvent extends javax.swing.JInternalFrame {
    
    static int updateID;    //Store Event ID for updtaing event
    
    public AddEvent() {
        initComponents();
        
        //remove frame of Internal Frame
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        //Change color of side bar panel
        EventFrame.jPanel7.setBackground(new Color (156,190,234));
        EventFrame.jPanel9.setBackground(new Color (102,0,102));
        
        //Hide update Button
        jButton2.setVisible(false);
        
        //hide Id column
        participanttable.getColumnModel().getColumn(0).setWidth(0);
        participanttable.getColumnModel().getColumn(0).setMinWidth(0);
        participanttable.getColumnModel().getColumn(0).setMaxWidth(0);
    }
    
    /**
     * Handle Interface in Updating Event
     * @param ID 
     */
    AddEvent(String ID) throws ParseException{
        initComponents();
        
        //remove frame of Internal Frame
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        //load event details
        update(ID);
        
        //Hide Add Button
        jButton5.setVisible(false);
        
//        jPanel5.setBackground(new Color(92,126,150,165));
//        jPanel4.setBackground(new Color(92,126,150,165));
//        jPanel3.setBackground(new Color(92,126,150,165));
        
        //hide ID column
        participanttable.getColumnModel().getColumn(0).setWidth(0);
        participanttable.getColumnModel().getColumn(0).setMinWidth(0);
        participanttable.getColumnModel().getColumn(0).setMaxWidth(0);
    }
    
    /**
     * load Event details when updating event
     * @param ID Event ID
     * @throws ParseException 
     */
    public static void update(String ID) throws ParseException{
        List l = EventController.update_getEvent(ID);
        SimpleDateFormat time = new SimpleDateFormat("hh:mm a");
        
        for(Object o:l){
            EventPlan items = (EventPlan)o;
            updateID = items.getEventId();
            ename.setText(items.getName());
            edate.setDate(items.getDate());
            estartTime.setValue(time .parse(items.getStartTime()));
            eendTime.setValue(time .parse(items.getEndTime()));
            elocation.setText(items.getLocation());
            eNOP.setValue(items.getNop());
        }
        
        //load particiapnt table
        participanttable.setModel(EventController.update_getContactTable(ID));
        
        //load Item table
        itemTable.setModel(EventController.update_getItemTable(ID));
        
        //load food table
        mainfoodtable.setModel(EventController.update_getFoodTable(ID));
        
        //load contact table
        mainbevlist.setModel(EventController.update_getBevTable(ID)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        eNOP = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        elocation = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        SpinnerDateModel smm = new SpinnerDateModel();
        eendTime = new javax.swing.JSpinner(smm);
        jLabel2 = new javax.swing.JLabel();
        SpinnerDateModel sm = new SpinnerDateModel();
        estartTime = new javax.swing.JSpinner(sm);
        jLabel4 = new javax.swing.JLabel();
        edate = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        ename = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainbevlist = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        mainfoodtable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        participanttable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();

        setBackground(java.awt.Color.white);
        setBorder(null);
        setForeground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(1280, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Add Participants");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, -110, -1, -1));

        jLabel8.setText("Foods & drinks");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, -110, -1, -1));

        jPanel1.setBackground(new java.awt.Color(156, 190, 234));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eNOP.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        eNOP.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        eNOP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(70, 105, 151), 2, true));
        jPanel1.add(eNOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 290, 40));

        jLabel6.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(70, 105, 151));
        jLabel6.setText("Number of participants");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        elocation.setBackground(new java.awt.Color(254, 254, 254));
        elocation.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        elocation.setForeground(new java.awt.Color(1, 1, 1));
        elocation.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        elocation.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(70, 105, 151), 2, true));
        jPanel1.add(elocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 290, 40));

        jLabel5.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(70, 105, 151));
        jLabel5.setText("Location");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        eendTime.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        eendTime.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(70, 105, 151), 2, true));
        jPanel1.add(eendTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 290, 40));
        JSpinner.DateEditor timeEditor2 = new JSpinner.DateEditor(eendTime, "hh:mm a");
        eendTime.setEditor(timeEditor2);

        jLabel2.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 105, 151));
        jLabel2.setText("End Time");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        estartTime.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        estartTime.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(70, 105, 151), 2, true));
        jPanel1.add(estartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 290, 40));
        JSpinner.DateEditor timeEditor = new JSpinner.DateEditor(estartTime, "hh:mm a");
        estartTime.setEditor(timeEditor);

        jLabel4.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(70, 105, 151));
        jLabel4.setText("Start Time");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        edate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(70, 105, 151), 2, true));
        edate.setForeground(new java.awt.Color(70, 105, 151));
        jPanel1.add(edate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 290, 40));

        jLabel3.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(70, 105, 151));
        jLabel3.setText("Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        ename.setBackground(new java.awt.Color(254, 254, 254));
        ename.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        ename.setForeground(new java.awt.Color(1, 1, 1));
        ename.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ename.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(70, 105, 151), 2, true));
        ename.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ename.setSelectionColor(new java.awt.Color(62, 155, 208));
        ename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enameActionPerformed(evt);
            }
        });
        jPanel1.add(ename, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 290, 40));

        jLabel1.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(70, 105, 151));
        jLabel1.setText("Event Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 600));

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Droid Sans", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(70, 105, 151));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\submitblue.png")); // NOI18N
        jButton2.setText("UPDATE EVENT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 270, 40));

        jPanel4.setBackground(new java.awt.Color(92, 126, 150));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Droid Sans", 1, 13)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\foodicon.png")); // NOI18N
        jButton3.setText("FOOD & BEVERAGES");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 7, 230, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("FOOD");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        mainbevlist.setBackground(new java.awt.Color(190, 188, 206));
        mainbevlist.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mainbevlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(mainbevlist);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 230, 170));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("BEVRAGES");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        mainfoodtable.setBackground(new java.awt.Color(190, 188, 206));
        mainfoodtable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mainfoodtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plate"
            }
        ));
        jScrollPane3.setViewportView(mainfoodtable);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 230, 160));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 280, 480));

        jPanel5.setBackground(new java.awt.Color(92, 126, 150));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\contacticon.png")); // NOI18N
        jButton1.setText("PARTICIPATIONS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 7, 230, 50));

        participanttable.setBackground(new java.awt.Color(190, 188, 206));
        participanttable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        participanttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address"
            }
        ));
        jScrollPane2.setViewportView(participanttable);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 230, 380));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 270, 480));

        jPanel3.setBackground(new java.awt.Color(92, 126, 150));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\itemsBlack.png")); // NOI18N
        jButton4.setText("      EVENT ITEMS            ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 7, 240, 50));

        itemTable.setBackground(new java.awt.Color(190, 188, 206));
        itemTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Quantity"
            }
        ));
        jScrollPane4.setViewportView(itemTable);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 240, 380));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 280, 480));

        jButton5.setFont(new java.awt.Font("Droid Sans", 1, 15)); // NOI18N
        jButton5.setForeground(new java.awt.Color(70, 105, 151));
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\submitblue.png")); // NOI18N
        jButton5.setText("    SUBMIT EVENT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 270, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 920, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        DateEditor de = new DateEditor(estartTime,"hh:mm a");
        
        String name;           //event Name
        Date date;             //event Date
        String startTime;      //event Start Time
        String endTime;        //event End Time
        String location;       //event Location
        String NOP;            //NUmber of participants
        
        name = ename.getText();
        date = edate.getDate();
        endTime = (de.getFormat().format(eendTime.getValue()));
        startTime = (de.getFormat().format(estartTime.getValue()));
        location = elocation.getText();
        NOP = eNOP.getValue().toString();
        
        EventPlan newEvent = new EventPlan();
        newEvent.setEventId(updateID);
    	newEvent.setName(name);
    	newEvent.setDate(date);
    	newEvent.setStartTime(startTime);
    	newEvent.setEndTime(endTime);
    	newEvent.setLocation(location);
    	newEvent.setNop(Integer.parseInt(NOP));
    	
        //update Event main details
        EventController.updateEvent(newEvent);
        
        //update Event contact details
        Eventncontact eventncontact = new Eventncontact();
        eventncontact.setEventId(updateID);
        EventController.deleteParticipantTable(updateID);
        for(int i=0;i<participanttable.getRowCount();i++){
            eventncontact.setName(participanttable.getValueAt(i, 0).toString());
            eventncontact.setAddress(participanttable.getValueAt(i, 1).toString());
            EventController.addParticipantTable(eventncontact);
        }
        
        //update Event Item details
        Eventnitems eventnitems = new Eventnitems();
        eventnitems.setEventId(updateID);
        EventController.deleteItemTable(updateID);
        for(int i=0;i<itemTable.getRowCount();i++){
            eventnitems.setItemName(itemTable.getValueAt(i, 0).toString());
            eventnitems.setQuantity(Integer.parseInt(itemTable.getValueAt(i, 1).toString()));
            EventController.addItemTable(eventnitems);
        }
        
        //update Event food details
        Eventnfood eventnfood = new Eventnfood();
        eventnfood.setEventId(updateID);
        EventController.deleteFoodTable(updateID);
        for(int i=0;i<mainfoodtable.getRowCount();i++){
            eventnfood.setPlate(mainfoodtable.getValueAt(i, 0).toString());
            EventController.addFoodTable(eventnfood);
        }
        
        //update Event beverage details
        Eventnbev eventnbev = new Eventnbev();
        eventnbev.setEventId(updateID);
        EventController.deleteBevTable(updateID);
        for(int i=0;i<mainbevlist.getRowCount();i++){
            eventnbev.setName(mainbevlist.getValueAt(i, 0).toString());
            eventnbev.setQuantity(Integer.parseInt(mainbevlist.getValueAt(i, 1).toString()));
            EventController.addBevTable(eventnbev);
        }
        
        //this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        //load event item interface
        EventItems items = new EventItems();
        items.setVisible(true);
        
        //load current item table to event item interface
        DefaultTableModel model = (DefaultTableModel) itemTable.getModel();
        EventItems.jTable1.setModel(model);
        
    }//GEN-LAST:event_jButton4ActionPerformed
    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //load event contact interface
        EventContact con = new EventContact();
        con.setVisible(true);
        
        //load current contact table to event contact interface
        DefaultTableModel model = (DefaultTableModel) participanttable.getModel();
        EventContact.jTable3.setModel(model);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        //load event food and beverage interface
        EventFood con = new EventFood();
        con.setVisible(true);
        
        //load current food table to event food interface
        DefaultTableModel model1 = (DefaultTableModel) mainfoodtable.getModel();
        EventFood.finalfoodlist.setModel(model1);
        
        //load current beverage table to event beverage interface
        DefaultTableModel model2 = (DefaultTableModel) mainbevlist.getModel();
        EventFood.finalbevlist.setModel(model2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        DateEditor de = new DateEditor(estartTime,"hh:mm a");
        
        String name;           //event Name
        Date date;             //event Date
        String startTime;      //event Start Time
        String endTime;        //event End Time
        String location;       //event Location
        String NOP;            //NUmber of participants
        
        name = ename.getText();
        date = edate.getDate();
        endTime = (de.getFormat().format(eendTime.getValue()));
        startTime = (de.getFormat().format(estartTime.getValue()));
        location = elocation.getText();
        NOP = eNOP.getValue().toString();
        
        EventPlan newEvent = new EventPlan();
    	newEvent.setName(name);
    	newEvent.setDate(date);
    	newEvent.setStartTime(startTime);
    	newEvent.setEndTime(endTime);
    	newEvent.setLocation(location);
    	newEvent.setNop(Integer.parseInt(NOP));
    	
        //Add event main details
        EventController.AddEvent(newEvent);
        
        //Add event contact details
        Eventncontact eventncontact = new Eventncontact();
        eventncontact.setEventId(newEvent.getEventId());
        for(int i=0;i<participanttable.getRowCount();i++){
            eventncontact.setName(participanttable.getValueAt(i, 0).toString());
            eventncontact.setAddress(participanttable.getValueAt(i, 1).toString());
            EventController.addParticipantTable(eventncontact);
        }
        
        //Add event item details
        Eventnitems eventnitems = new Eventnitems();
        eventnitems.setEventId(newEvent.getEventId());
        for(int i=0;i<itemTable.getRowCount();i++){
            eventnitems.setItemName(itemTable.getValueAt(i, 0).toString());
            eventnitems.setQuantity(Integer.parseInt(itemTable.getValueAt(i, 1).toString()));
            EventController.addItemTable(eventnitems);
        }
        
        //Add event food details
        Eventnfood eventnfood = new Eventnfood();
        eventnfood.setEventId(newEvent.getEventId());
        for(int i=0;i<mainfoodtable.getRowCount();i++){
            eventnfood.setPlate(mainfoodtable.getValueAt(i, 0).toString());
            EventController.addFoodTable(eventnfood);
        }
        
        //Add event beverage details
        Eventnbev eventnbev = new Eventnbev();
        eventnbev.setEventId(newEvent.getEventId());
        for(int i=0;i<mainbevlist.getRowCount();i++){
            eventnbev.setName(mainbevlist.getValueAt(i, 0).toString());
            eventnbev.setQuantity(Integer.parseInt(mainbevlist.getValueAt(i, 1).toString()));
            EventController.addBevTable(eventnbev);
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JSpinner eNOP;
    public static com.toedter.calendar.JDateChooser edate;
    public static javax.swing.JSpinner eendTime;
    public static javax.swing.JTextField elocation;
    public static javax.swing.JTextField ename;
    public static javax.swing.JSpinner estartTime;
    public static javax.swing.JTable itemTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTable mainbevlist;
    public static javax.swing.JTable mainfoodtable;
    public static javax.swing.JTable participanttable;
    // End of variables declaration//GEN-END:variables
}
