/*
 * Copyright (c) 2016 SLIIT, All Rights Reserved.
 * HOME MANAGEMENT SYSTEM
 * SEP GROUP PROJECT - 3rd YEAR
 *
 */
package view.event;

import controller.event.EventItemController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.event.EventItems;

/**
 * EditEventItems -- Interface for Edit Event Items
 * @author Isurunath
 */
public class EditEventItems extends javax.swing.JFrame {
    DefaultTableModel model; //store table model
    
    public EditEventItems() {
    	initComponents();
    }
    
    EditEventItems(DefaultTableModel m){
        initComponents();
        loadcombo(); //load comboBox
        displaytable(); //load Table
        model = m;
    }
    
    /**
     * Load ComboBox
     */
    public static void loadcombo() {
        List l = EventItemController.LoadcomboList();
        jComboBox1.removeAllItems();
        jComboBox1.addItem("All catagories");
        for(Object o : l) {
            jComboBox1.addItem(o);
        }
    }
    
    /**
     * Load Event table
     */
    public static void displaytable(){
    	
        String catagory = jComboBox1.getSelectedItem().toString();
    	jTable1.setModel(EventItemController.LoadItemTable(catagory));
        
        //hide ID column in table
        jTable1.getColumnModel().getColumn(5).setWidth(0);
        jTable1.getColumnModel().getColumn(5).setMinWidth(0);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(0);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iname = new javax.swing.JTextField();
        icatagory = new javax.swing.JTextField();
        iprice = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        icontact = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        iaddress = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iname.setForeground(new java.awt.Color(1, 1, 1));
        iname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        iname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(70, 105, 151), 2, true));
        iname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inameActionPerformed(evt);
            }
        });
        getContentPane().add(iname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 160, 30));

        icatagory.setForeground(new java.awt.Color(1, 1, 1));
        icatagory.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        icatagory.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(70, 105, 151), 2, true));
        getContentPane().add(icatagory, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 160, 30));

        iprice.setForeground(new java.awt.Color(1, 1, 1));
        iprice.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        iprice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(70, 105, 151), 2, true));
        getContentPane().add(iprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 160, 30));

        jPanel1.setBackground(new java.awt.Color(190, 212, 228));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Supplier Details"));
        jPanel1.setForeground(new java.awt.Color(130, 147, 203));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Droid Sans", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(70, 105, 151));
        jLabel5.setText("Address");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Droid Sans", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(70, 105, 151));
        jLabel6.setText("Contact");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        icontact.setForeground(new java.awt.Color(1, 1, 1));
        icontact.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        icontact.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(70, 105, 151), 2, true));
        jPanel1.add(icontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 160, 30));

        iaddress.setColumns(20);
        iaddress.setForeground(new java.awt.Color(1, 1, 1));
        iaddress.setRows(5);
        iaddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(70, 105, 151), 2, true));
        jScrollPane2.setViewportView(iaddress);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 160, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 310, 220));

        jTable1.setBackground(new java.awt.Color(193, 193, 193));
        jTable1.setForeground(new java.awt.Color(1, 1, 1));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Catagory", "Item Name", "Quantity"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 430, 300));

        jPanel2.setBackground(new java.awt.Color(92, 126, 150));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 204, 102));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\updateYelllow.png")); // NOI18N
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 150, 35));

        jButton1.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\addBlue.png")); // NOI18N
        jButton1.setText("ADD TO LIST");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 150, 35));

        jLabel3.setFont(new java.awt.Font("Droid Sans", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Price(Rs.)");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Droid Sans", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Event Catagory");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Droid Sans", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Item Name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 450));

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\backWhite.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, 30));

        jButton2.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\deleteRed.png")); // NOI18N
        jButton2.setText("DELTE ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 150, 35));

        jComboBox1.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(1, 1, 1));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All catagories" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBox1MouseReleased(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 160, 30));

        jLabel7.setFont(new java.awt.Font("Droid Sans", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(1, 1, 1));
        jLabel7.setText("Item Catagory");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 480, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inameActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        //set selected row values to the textBoxes
        int i = jTable1.getSelectedRow();
        iname.setText(jTable1.getValueAt(i, 0).toString());
        icatagory.setText(jTable1.getValueAt(i, 1).toString());
        iprice.setText(jTable1.getValueAt(i, 2).toString());
        iaddress.setText(jTable1.getValueAt(i, 3).toString());
        icontact.setText(jTable1.getValueAt(i, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseReleased
        
    	displaytable(); //refreash table on comboBox selection
    }//GEN-LAST:event_jComboBox1MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String name;          //Item name
        String catagory;      //Item catagory
        String price;         //Item price
        String address;       //Item supplier address
        String contact;       //Item supplier contact
        
        name = iname.getText();
        catagory = icatagory.getText();
        price = iprice.getText();
        address = iaddress.getText();
        contact = icontact.getText();
        
        //setting values to a EventItem object
        EventItems item = new EventItems();
        item.setItemName(name);
        item.setEventCatagory(catagory);
        item.setAddress(address);
        item.setPrice(price);
        item.setContact(contact);
        
        DefaultTableModel d = new DefaultTableModel();
        d = (DefaultTableModel) jTable1.getModel();
        
        //Adding new Item
        EventItemController.addEventItem(d,item);
        displaytable();  //Refreash table 
        loadcombo();  //refreash combobox
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Do you want to continue?", "Confirm",
                                                     JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (response == JOptionPane.YES_OPTION) {
            //Delete item
            int i = jTable1.getSelectedRow();
            EventItemController.DeleteItems(jTable1.getValueAt(i, 5).toString());
            
            displaytable();  //Refreash table 
            loadcombo();  //refreash combobox
            
            //Clear textBoxes
            iname.setText("");
            icatagory.setText("");
            iprice.setText("");
            iaddress.setText("");
            icontact.setText("");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //display back to Event Item interface
        view.event.EventItems ei = new view.event.EventItems();
        ei.setVisible(true);
        view.event.EventItems.jTable1.setModel(model);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int i = jTable1.getSelectedRow();
        String ID = jTable1.getValueAt(i, 5).toString();
        
        String name;          //Item name
        String catagory;      //Item catagory
        String price;         //Item price
        String address;       //Item supplier address
        String contact;       //Item supplier contact
        
        name = iname.getText();
        catagory = icatagory.getText();
        price = iprice.getText();
        address = iaddress.getText();
        contact = icontact.getText();
        
        //setting values to a EventItem object
        EventItems item = new EventItems();
        item.setId(Integer.parseInt(ID));
        item.setItemName(name);
        item.setEventCatagory(catagory);
        item.setAddress(address);
        item.setPrice(price);
        item.setContact(contact);
       
        //Update Item
        EventItemController.updateItem(item);
        displaytable();  //Refreash table 
        loadcombo();  //refreash combobox

    }//GEN-LAST:event_jButton4ActionPerformed

    /**EventItemController.loadedititems();
        EventItemController.LoadItemTable();
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEventItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEventItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEventItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEventItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEventItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea iaddress;
    private javax.swing.JTextField icatagory;
    private javax.swing.JTextField icontact;
    private javax.swing.JTextField iname;
    private javax.swing.JTextField iprice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private static javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

	
}
