/*
 * Copyright (c) 2016 SLIIT, All Rights Reserved.
 * HOME MANAGEMENT SYSTEM
 * SEP GROUP PROJECT - 3rd YEAR
 *
 */
package view.event;

import controller.event.EventFoodController;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 * EventFood -- Interface for Event Food interface
 * @author Isurunath
 */
public class EventFood extends javax.swing.JFrame {

    public EventFood() {
        initComponents();
        loadcombo();    //Load boxes of food and beverages
        loadFoodList(); //Load Food List
        loadBevList();  //Load Beverage List
    }
    
    /**
     * Load boxes of food and beverages
     */
    public static void loadcombo(){
    	List l = EventFoodController.LoadFoodcombo();
        List s = EventFoodController.LoadBevcombo();
        for(Object o : l) {
            foodCombo.addItem(o);
        }
        
        for(Object o : s) {
            BevCombo.addItem(o);
        }
    }
    
    /**
     * Load Food List
     */
    public static void loadFoodList(){
    	DefaultListModel df = new DefaultListModel();
    	String catagory = (foodCombo.getSelectedItem().toString());
    	List l = EventFoodController.loadFoodList(catagory);
    	
    	for(Object o : l) {
            df.addElement(o);
        }
    	foodlist.setModel(df);
    }
    
    /**
     * Load Beverage List
     */
    public static void loadBevList(){
    	DefaultListModel df = new DefaultListModel();
    	String catagory = (BevCombo.getSelectedItem().toString());
    	List l = EventFoodController.loadBevList(catagory);
    	
    	for(Object o : l) {
            df.addElement(o);
        }
    	bevlist.setModel(df);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        foodlist = new javax.swing.JList();
        jPanel6 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        qty1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        foodCombo = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        finalfoodlist = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bevlist = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        qty = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        BevCombo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        finalbevlist = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(92, 126, 150));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foodlist.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        jScrollPane5.setViewportView(foodlist);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 220, 260));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 1, 1)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\addBlue.png")); // NOI18N
        jButton5.setText("ADD >>");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 40));

        jButton6.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(1, 1, 1));
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\deleteRed.png")); // NOI18N
        jButton6.setText("Remove");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 40));

        qty1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        qty1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qty1MouseClicked(evt);
            }
        });
        qty1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                qty1PropertyChange(evt);
            }
        });
        jPanel6.add(qty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, 30));

        jLabel3.setFont(new java.awt.Font("Droid Sans", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("Number of plates");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 160, 260));

        foodCombo.setFont(new java.awt.Font("Droid Sans", 1, 13)); // NOI18N
        foodCombo.setForeground(new java.awt.Color(1, 1, 1));
        foodCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All catagories" }));
        foodCombo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                foodComboMouseDragged(evt);
            }
        });
        foodCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foodComboMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                foodComboMouseReleased(evt);
            }
        });
        foodCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodComboActionPerformed(evt);
            }
        });
        jPanel4.add(foodCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 220, -1));

        jPanel7.setBackground(new java.awt.Color(254, 254, 254));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        finalfoodlist.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finalfoodlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        finalfoodlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finalfoodlistMouseClicked(evt);
            }
        });
        finalfoodlist.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                finalfoodlistPropertyChange(evt);
            }
        });
        jScrollPane6.setViewportView(finalfoodlist);

        jPanel7.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 250, 260));

        jButton4.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(70, 105, 151));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\submitblue.png")); // NOI18N
        jButton4.setText("    CONFIRM");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 250, 40));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 320, 440));

        jLabel1.setFont(new java.awt.Font("Droid Sans", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("Select Menu");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\edit.png")); // NOI18N
        jButton9.setText("CUTOMIZE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 30));

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 440));

        jTabbedPane1.addTab("FOOD", jPanel5);

        jPanel2.setBackground(new java.awt.Color(92, 126, 150));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bevlist.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        bevlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bevlistMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(bevlist);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 220, 260));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 1, 1)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\addBlue.png")); // NOI18N
        jButton1.setText("ADD >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 40));

        jButton2.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(1, 1, 1));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\deleteRed.png")); // NOI18N
        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 40));

        qty.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        qty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                qtyStateChanged(evt);
            }
        });
        qty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qtyMouseClicked(evt);
            }
        });
        qty.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                qtyPropertyChange(evt);
            }
        });
        jPanel1.add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, 30));

        jLabel2.setFont(new java.awt.Font("Droid Sans", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("Quantity");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 160, 260));

        BevCombo.setFont(new java.awt.Font("Droid Sans", 1, 13)); // NOI18N
        BevCombo.setForeground(new java.awt.Color(1, 1, 1));
        BevCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All catagories" }));
        BevCombo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BevComboMouseDragged(evt);
            }
        });
        BevCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BevComboMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BevComboMouseReleased(evt);
            }
        });
        BevCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BevComboActionPerformed(evt);
            }
        });
        jPanel2.add(BevCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 220, -1));

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        finalbevlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        finalbevlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finalbevlistMouseClicked(evt);
            }
        });
        finalbevlist.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                finalbevlistPropertyChange(evt);
            }
        });
        jScrollPane4.setViewportView(finalbevlist);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 250, 260));

        jButton7.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(70, 105, 151));
        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\submitblue.png")); // NOI18N
        jButton7.setText("    CONFIRM");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 250, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 310, 450));

        jLabel4.setFont(new java.awt.Font("Droid Sans", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("Select Catgory");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\edit.png")); // NOI18N
        jButton3.setText("CUTOMIZE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 21, -1, 30));

        jTabbedPane1.addTab("BEVERAGES", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void finalbevlistPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_finalbevlistPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_finalbevlistPropertyChange

    private void finalbevlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finalbevlistMouseClicked
        
        //setting quantity according to selected row
        int r=finalbevlist.getSelectedRow();
        String quantity =finalbevlist.getValueAt(r, 1).toString();
        qty.setValue(Integer.parseInt(quantity));
    }//GEN-LAST:event_finalbevlistMouseClicked

    private void BevComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BevComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BevComboActionPerformed

    private void BevComboMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BevComboMouseReleased
        //refreash BeverageList
        loadBevList();
    }//GEN-LAST:event_BevComboMouseReleased

    private void BevComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BevComboMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_BevComboMouseClicked

    private void BevComboMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BevComboMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_BevComboMouseDragged

    private void qtyPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_qtyPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyPropertyChange

    private void qtyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qtyMouseClicked

        //        int r=jTable1.getSelectedRow();
        //        jTable1.setValueAt(evt, r, 1);
    }//GEN-LAST:event_qtyMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        //remove item from selected beverage list
        DefaultTableModel model = (DefaultTableModel) finalbevlist.getModel();
        model.removeRow(finalbevlist.getSelectedRow());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //Add Beverage to Final List
        DefaultTableModel table = new DefaultTableModel();
        table = (DefaultTableModel) finalbevlist.getModel();
        
        Object quantity = qty.getValue();
        String newitem = bevlist.getSelectedValue().toString();
        
        // adding to the beverage list after cheking weather it exist or not
        finalbevlist.setModel(EventFoodController.addtotable(table,quantity,newitem));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void finalfoodlistPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_finalfoodlistPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_finalfoodlistPropertyChange

    private void finalfoodlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finalfoodlistMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_finalfoodlistMouseClicked

    private void foodComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodComboActionPerformed

    private void foodComboMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodComboMouseReleased
        //refreash FoodList
        loadFoodList();
    }//GEN-LAST:event_foodComboMouseReleased

    private void foodComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodComboMouseClicked
        
    }//GEN-LAST:event_foodComboMouseClicked

    private void foodComboMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodComboMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_foodComboMouseDragged

    private void qty1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_qty1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_qty1PropertyChange

    private void qty1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qty1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_qty1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        //remove item from selected food list
        DefaultTableModel model = (DefaultTableModel) finalfoodlist.getModel();
        model.removeRow(finalfoodlist.getSelectedRow());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        //Add Food to Final List
        DefaultTableModel d = new DefaultTableModel();
        d = (DefaultTableModel) finalfoodlist.getModel();
        d.addRow(new Object[] { foodlist.getSelectedValue()});
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
        //load food and beverage settings
        EditEventFood eef = new EditEventFood();
        eef.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        //load food and beverage settings
        EditEventFood eef = new EditEventFood();
        eef.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //exit
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void bevlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bevlistMouseClicked
        finalbevlist.clearSelection();  //clear selection in selected beverage list table
        qty.setValue(((Number)1).intValue());  //change quantity to 1
    }//GEN-LAST:event_bevlistMouseClicked

    private void qtyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_qtyStateChanged
        int r=finalbevlist.getSelectedRow();
        
        //change the quantity in selected table items
        if(r!=-1){
            finalbevlist.setValueAt(qty.getValue(), r, 1);
        }
    }//GEN-LAST:event_qtyStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventFood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox BevCombo;
    private static javax.swing.JList bevlist;
    public static javax.swing.JTable finalbevlist;
    public static javax.swing.JTable finalfoodlist;
    public static javax.swing.JComboBox foodCombo;
    private static javax.swing.JList foodlist;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner qty;
    private javax.swing.JSpinner qty1;
    // End of variables declaration//GEN-END:variables
}
