/*
 * Copyright (c) 2016 SLIIT, All Rights Reserved.
 * HOME MANAGEMENT SYSTEM
 * SEP GROUP PROJECT - 3rd YEAR
 *
 */
package view.event;

import controller.event.EventController;
import java.awt.Color;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 * SearchEvents -- Interface for Search Events
 * @author Isurunath
 */
public class SearchEvents extends javax.swing.JInternalFrame {

    public SearchEvents() {
        initComponents();
        
        displayTable("ALL"); //Load table for displaying all events
        
        //remove frame of internal frame
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        //Change color of side bar panel
        EventFrame.jPanel7.setBackground(new Color (102,0,102));
        EventFrame.jPanel9.setBackground(new Color (156,190,234));
    }
    
    /**
     * Display Event Table
     */
    public static void displayTable(String time){
        jTable1.setModel(EventController.displayTable(time));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        today = new javax.swing.JRadioButton();
        past = new javax.swing.JRadioButton();
        upcoming = new javax.swing.JRadioButton();
        all = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1280, 634));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(156, 190, 234));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(153, 153, 255));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 980, 470));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        today.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        today.setText("Today Events");
        today.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                todayMouseClicked(evt);
            }
        });
        jPanel2.add(today, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        past.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        past.setText("Past Events");
        past.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pastMouseClicked(evt);
            }
        });
        jPanel2.add(past, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        upcoming.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        upcoming.setText("Upcoming Events");
        upcoming.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upcomingMouseClicked(evt);
            }
        });
        jPanel2.add(upcoming, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        all.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        all.setText("All Events");
        all.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allMouseClicked(evt);
            }
        });
        jPanel2.add(all, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 980, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 610));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\deleteRed.png")); // NOI18N
        jButton1.setText("DELETE EVENT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 204, 0));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\updateYelllow.png")); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 150, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 240, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Do you want to continue?", "Confirm",
                                                     JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
            if (response == JOptionPane.YES_OPTION) {
            //delete selected event
            int i = jTable1.getSelectedRow();
            EventController.DeleteEvent(jTable1.getValueAt(i, 0).toString());
            displayTable("ALL");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void upcomingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upcomingMouseClicked
        
        //refreash table with upcoming events
        displayTable("UPCOMING");
        today.setSelected(false);
        past.setSelected(false);
        all.setSelected(false);
    }//GEN-LAST:event_upcomingMouseClicked

    private void pastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pastMouseClicked
        
        //refreash table with past events
        displayTable("PAST");
        upcoming.setSelected(false);
        today.setSelected(false);
        all.setSelected(false);
    }//GEN-LAST:event_pastMouseClicked

    private void todayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_todayMouseClicked
        
        //refreash table with today events
        displayTable("TODAY");
        upcoming.setSelected(false);
        past.setSelected(false);
        all.setSelected(false);
    }//GEN-LAST:event_todayMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        //load update interface for selected event
        int i = jTable1.getSelectedRow();
        String ID = jTable1.getValueAt(i, 0).toString();
        UpdateEvent ue = null;
        try {
            ue = new UpdateEvent(ID);
        } catch (ParseException ex) {
            Logger.getLogger(SearchEvents.class.getName()).log(Level.SEVERE, null, ex);
        }
        ue.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void allMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allMouseClicked
        
        //refreash table with All events
        displayTable("ALL");
        upcoming.setSelected(false);
        past.setSelected(false);
        today.setSelected(false);
    }//GEN-LAST:event_allMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton all;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JRadioButton past;
    private javax.swing.JRadioButton today;
    private javax.swing.JRadioButton upcoming;
    // End of variables declaration//GEN-END:variables
}
