package model.Inventory;
// Generated Apr 3, 2016 11:17:17 AM by Hibernate Tools 4.3.1



/**
 * Otheritem generated by hbm2java
 */
public class Otheritem  implements java.io.Serializable {


     private String itemCode;
     private String name;
     private String location;
     private int qty;
     private double price;
     private String user;
     private String date;
     private String description;
     private String usage;
     private String status;

    public Otheritem() {
    }

	
    public Otheritem(String itemCode, String name, String location, int qty, double price, String user) {
        this.itemCode = itemCode;
        this.name = name;
        this.location = location;
        this.qty = qty;
        this.price = price;
        this.user = user;
    }
    
    public Otheritem(String itemCode, String name, String location, int qty, double price, String user, String date, String description, String usage, String status) {
       this.itemCode = itemCode;
       this.name = name;
       this.location = location;
       this.qty = qty;
       this.price = price;
       this.user = user;
       this.date = date;
       this.description = description;
       this.usage = usage;
       this.status = status;
    }
    
    public Otheritem(String itemCode, String name, String location, int qty, double price, String user, String date, String description, String usage) {
       this.itemCode = itemCode;
       this.name = name;
       this.location = location;
       this.qty = qty;
       this.price = price;
       this.user = user;
       this.date = date;
       this.description = description;
       this.usage = usage;
    }

   
    public String getItemCode() {
        return this.itemCode;
    }
    
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getUsage() {
        return this.usage;
    }
    
    public void setUsage(String usage) {
        this.usage = usage;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


