/*
 * Copyright (c) 2016 SLIIT, All Rights Reserved.
 * HOME MANAGEMENT SYSTEM
 * SEP GROUP PROJECT - 3rd YEAR
 *
 */
package view.Inventory.Main;

import View.Inventory.Book.AddNewBook;
import View.Inventory.Book.DeleteBook;
import View.Inventory.Book.SearchBook;
import View.Inventory.Book.UpdateBook;
import View.Inventory.ElectricGoods.AddNewElectricGoods;
import View.Inventory.ElectricGoods.DeleteElectricGoods;
import View.Inventory.ElectricGoods.SearchElectricGoods;
import View.Inventory.ElectricGoods.UpdateElectricGoods;
import View.Inventory.Furniture.AddNewFurniture;
import View.Inventory.Furniture.DeleteFurniture;
import View.Inventory.Furniture.SearchFurniture;
import View.Inventory.Furniture.UpdateFurniture;
import View.Inventory.GarmentAndAccessory.AddNewGarmentAndAccesory;
import View.Inventory.GarmentAndAccessory.DeleteGarmentAndAccesory;
import View.Inventory.GarmentAndAccessory.SearchGarmentAndAccesory;
import View.Inventory.GarmentAndAccessory.UpdateGarmentAndAccesory;
import View.Inventory.Medicine.AddNewMedicine;
import View.Inventory.Medicine.DeleteMedicine;
import View.Inventory.Medicine.SearchMedicine;
import View.Inventory.Medicine.UpdateMedicine;
import View.Inventory.OtherItem.AddNewOtherItem;
import View.Inventory.OtherItem.DeleteOtherItem;
import View.Inventory.OtherItem.SearchOtherItem;
import View.Inventory.OtherItem.UpdateOtherItem;
import View.Inventory.Repair.AddNewRepair;
import View.Inventory.Repair.DeleteRepair;
import View.Inventory.Repair.SearchRepair;
import View.Inventory.Repair.UpdateRepair;
import View.Inventory.Tool.AddNewTool;
import View.Inventory.Tool.DeleteTool;
import View.Inventory.Tool.SearchTool;
import View.Inventory.Tool.UpdateTool;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.text.Position;

/**
 * InventoryFrame -- Interface for Home Event Handling
 * @author Nipuni
 */
public class InventoryFrame1 extends javax.swing.JInternalFrame {
    private static String buttonRespond="";

    public InventoryFrame1() {
        initComponents();
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        FrontDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        updateSearchText = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        FrontDesktopPane3 = new javax.swing.JDesktopPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jButton3 = new javax.swing.JButton();
        deleteSearchText = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        FrontDesktopPane4 = new javax.swing.JDesktopPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        searchText = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        FrontDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        addSearchText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBorder(null);
        setMinimumSize(new java.awt.Dimension(1370, 553));
        setPreferredSize(new java.awt.Dimension(1365, 590));

        jPanel1.setPreferredSize(new java.awt.Dimension(1365, 590));

        jTabbedPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 204), 3, true));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setInheritsPopupMenu(true);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1365, 590));

        jPanel5.setBackground(java.awt.Color.white);

        FrontDesktopPane2.setPreferredSize(new java.awt.Dimension(1073, 580));

        javax.swing.GroupLayout FrontDesktopPane2Layout = new javax.swing.GroupLayout(FrontDesktopPane2);
        FrontDesktopPane2.setLayout(FrontDesktopPane2Layout);
        FrontDesktopPane2Layout.setHorizontalGroup(
            FrontDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1073, Short.MAX_VALUE)
        );
        FrontDesktopPane2Layout.setVerticalGroup(
            FrontDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPanel6.setPreferredSize(new java.awt.Dimension(236, 580));

        jList2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jList2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jList2.setForeground(new java.awt.Color(102, 0, 153));
        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Electrical Items", "Furniture", "Books", "Tools", "Garments Or Accessories", "Other items", "Repairs", "Medicine" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jList2.setDragEnabled(true);
        jList2.setFixedCellHeight(50);
        jList2.setPreferredSize(new java.awt.Dimension(160, 392));
        jList2.setSelectedIndex(0);
        jList2.setSelectionBackground(new java.awt.Color(167, 223, 223));
        jList2.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jList2MouseEntered(evt);
            }
        });
        jList2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jList2FocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        updateSearchText.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        updateSearchText.setText("Search");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(updateSearchText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateSearchText)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FrontDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addComponent(FrontDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/images/User/updateYelllow.png")), jPanel5); // NOI18N

        jPanel7.setBackground(java.awt.Color.white);

        FrontDesktopPane3.setPreferredSize(new java.awt.Dimension(1073, 580));

        javax.swing.GroupLayout FrontDesktopPane3Layout = new javax.swing.GroupLayout(FrontDesktopPane3);
        FrontDesktopPane3.setLayout(FrontDesktopPane3Layout);
        FrontDesktopPane3Layout.setHorizontalGroup(
            FrontDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1073, Short.MAX_VALUE)
        );
        FrontDesktopPane3Layout.setVerticalGroup(
            FrontDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPanel8.setPreferredSize(new java.awt.Dimension(236, 580));

        jList3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jList3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jList3.setForeground(new java.awt.Color(102, 0, 153));
        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Electrical Items", "Furniture", "Books", "Tools", "Garments Or Accessories", "Other items", "Repairs", "Medicine" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jList3.setDragEnabled(true);
        jList3.setFixedCellHeight(50);
        jList3.setPreferredSize(new java.awt.Dimension(160, 392));
        jList3.setSelectedIndex(0);
        jList3.setSelectionBackground(new java.awt.Color(167, 223, 223));
        jList3.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jList3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jList3FocusGained(evt);
            }
        });
        jScrollPane3.setViewportView(jList3);

        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton3.setText("Ok");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        deleteSearchText.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        deleteSearchText.setText("Search");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(deleteSearchText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(deleteSearchText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FrontDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FrontDesktopPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/images/User/deleteRed.png")), jPanel7); // NOI18N

        jPanel9.setBackground(java.awt.Color.white);

        FrontDesktopPane4.setPreferredSize(new java.awt.Dimension(1073, 580));

        javax.swing.GroupLayout FrontDesktopPane4Layout = new javax.swing.GroupLayout(FrontDesktopPane4);
        FrontDesktopPane4.setLayout(FrontDesktopPane4Layout);
        FrontDesktopPane4Layout.setHorizontalGroup(
            FrontDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1065, Short.MAX_VALUE)
        );
        FrontDesktopPane4Layout.setVerticalGroup(
            FrontDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPanel10.setBackground(java.awt.Color.white);
        jPanel10.setPreferredSize(new java.awt.Dimension(236, 580));

        jList4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jList4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jList4.setForeground(new java.awt.Color(102, 0, 153));
        jList4.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Electrical Items", "Furniture", "Books", "Tools", "Garments Or Accessories", "Other items", "Repairs", "Medicine" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList4.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jList4.setDragEnabled(true);
        jList4.setFixedCellHeight(50);
        jList4.setSelectedIndex(0);
        jList4.setSelectionBackground(new java.awt.Color(167, 223, 223));
        jList4.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jList4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jList4FocusGained(evt);
            }
        });
        jScrollPane4.setViewportView(jList4);

        searchText.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        searchText.setText("Search");

        jButton4.setBackground(java.awt.Color.white);
        jButton4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton4.setText("Ok");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addGap(6, 6, 6))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(FrontDesktopPane4, 1065, 1065, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FrontDesktopPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/images/User/Search_32x32.png")), jPanel9); // NOI18N

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setPreferredSize(new java.awt.Dimension(1370, 590));

        FrontDesktopPane1.setPreferredSize(new java.awt.Dimension(1073, 580));

        javax.swing.GroupLayout FrontDesktopPane1Layout = new javax.swing.GroupLayout(FrontDesktopPane1);
        FrontDesktopPane1.setLayout(FrontDesktopPane1Layout);
        FrontDesktopPane1Layout.setHorizontalGroup(
            FrontDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1073, Short.MAX_VALUE)
        );
        FrontDesktopPane1Layout.setVerticalGroup(
            FrontDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setPreferredSize(new java.awt.Dimension(236, 580));

        jList1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jList1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(102, 0, 153));
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Electrical Items", "Furniture", "Books", "Tools", "Garments Or Accessories", "Other items", "Repairs", "Medicine" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jList1.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        jList1.setDragEnabled(true);
        jList1.setFixedCellHeight(50);
        jList1.setSelectedIndex(0);
        jList1.setSelectionBackground(new java.awt.Color(167, 223, 223));
        jList1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jList1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jList1FocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        addSearchText.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        addSearchText.setText("Search");
        addSearchText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addSearchTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addSearchTextMouseEntered(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(addSearchText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(addSearchText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(FrontDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(FrontDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("", new javax.swing.ImageIcon(getClass().getResource("/images/User/addBlue.png")), jPanel2); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name=addSearchText.getText();
        int index=jList1.getNextMatch(name, 0, Position.Bias.Forward);
        if(index!=-1){
       jList1.setSelectedValue(name, true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String name=updateSearchText.getText();
        int index=jList2.getNextMatch(name, 0, Position.Bias.Forward);
        if(index!=-1){
       jList2.setSelectedValue(name, true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            String name=deleteSearchText.getText();
            int index=jList3.getNextMatch(name, 0, Position.Bias.Forward);
            if(index!=-1){
           jList3.setSelectedValue(name, true);
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            String name=searchText.getText();
            int index=jList4.getNextMatch(name, 0, Position.Bias.Forward);
            if(index!=-1){
           jList4.setSelectedValue(name, true);
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jList2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseEntered

    }//GEN-LAST:event_jList2MouseEntered

    private void jList2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList2FocusGained
        String selection=String.valueOf(jList2.getSelectedValue());
        
        if("Electrical Items".equals(selection)){
               FrontDesktopPane2.removeAll();
               UpdateElectricGoods update=new UpdateElectricGoods(this.FrontDesktopPane2);
               FrontDesktopPane2.add(update);
               update.show();
        }else if("Furniture".equals(selection)){
            FrontDesktopPane2.removeAll();
            UpdateFurniture updatefur=new UpdateFurniture(this.FrontDesktopPane2);
            FrontDesktopPane2.add(updatefur);
            updatefur.show(); 
        }else if("Books".equals(selection)){
            FrontDesktopPane2.removeAll();
            UpdateBook updatebook=new UpdateBook(this.FrontDesktopPane2);
            FrontDesktopPane2.add(updatebook);
            updatebook.show();
        }else if("Tools".equals(selection)){
            FrontDesktopPane2.removeAll();
            UpdateTool updatetool=new UpdateTool(this.FrontDesktopPane2);
            FrontDesktopPane2.add(updatetool);
            updatetool.show();
        }else if("Garments Or Accessories".equals(selection)){
            FrontDesktopPane2.removeAll();
            UpdateGarmentAndAccesory updategaa=new UpdateGarmentAndAccesory(this.FrontDesktopPane2);
            FrontDesktopPane2.add(updategaa);
            updategaa.show(); 
        }else if("Other items".equals(selection)){
            FrontDesktopPane2.removeAll();
            UpdateOtherItem updateother=new UpdateOtherItem(this.FrontDesktopPane2);
            FrontDesktopPane2.add(updateother);
            updateother.show(); 
        }else if("Repairs".equals(selection)){
            FrontDesktopPane2.removeAll();
            UpdateRepair updaterepair=new UpdateRepair(this.FrontDesktopPane2);
            FrontDesktopPane2.add(updaterepair);
            updaterepair.show();         
        }else if("Medicine".equals(selection)){
            FrontDesktopPane2.removeAll();
            UpdateMedicine updatemedicine=new UpdateMedicine(this.FrontDesktopPane2);
            FrontDesktopPane2.add(updatemedicine);
            updatemedicine.show();   
        }
    }//GEN-LAST:event_jList2FocusGained

    private void addSearchTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSearchTextMouseEntered

    }//GEN-LAST:event_addSearchTextMouseEntered

    private void addSearchTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSearchTextMouseClicked
                addSearchText.setText("");
    }//GEN-LAST:event_addSearchTextMouseClicked

    private void jList1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList1FocusGained
        String selection=String.valueOf(jList1.getSelectedValue());
        
        if("Electrical Items".equals(selection)){
               FrontDesktopPane1.removeAll();
               AddNewElectricGoods addNew=new AddNewElectricGoods(this.FrontDesktopPane1);
               FrontDesktopPane1.add(addNew);
               addNew.show();
        }else if("Furniture".equals(selection)){
            FrontDesktopPane1.removeAll();
            AddNewFurniture addNewfur=new AddNewFurniture(this.FrontDesktopPane1);
            FrontDesktopPane1.add(addNewfur);
            addNewfur.show(); 
        }else if("Books".equals(selection)){
            FrontDesktopPane1.removeAll();
            AddNewBook addNewbook=new AddNewBook(this.FrontDesktopPane1);
            FrontDesktopPane1.add(addNewbook);
            addNewbook.show();
        }else if("Tools".equals(selection)){
            FrontDesktopPane1.removeAll();
            AddNewTool addNewtool=new AddNewTool(this.FrontDesktopPane1);
            FrontDesktopPane1.add(addNewtool);
            addNewtool.show();
        }else if("Garments Or Accessories".equals(selection)){
            FrontDesktopPane1.removeAll();
            AddNewGarmentAndAccesory addNewgaa=new AddNewGarmentAndAccesory(this.FrontDesktopPane1);
           FrontDesktopPane1.add(addNewgaa);
            addNewgaa.show(); 
        }else if("Other items".equals(selection)){
            FrontDesktopPane1.removeAll();
            AddNewOtherItem addNewother=new AddNewOtherItem(this.FrontDesktopPane1);
            FrontDesktopPane1.add(addNewother);
            addNewother.show(); 
        }else if("Repairs".equals(selection)){
            FrontDesktopPane1.removeAll();
            AddNewRepair addNewrepair=new AddNewRepair(this.FrontDesktopPane1);
            FrontDesktopPane1.add(addNewrepair);
            addNewrepair.show();         
        }else if("Medicine".equals(selection)){
            FrontDesktopPane1.removeAll();
            AddNewMedicine addNewmedicine=new AddNewMedicine(this.FrontDesktopPane1);
            FrontDesktopPane1.add(addNewmedicine);
            addNewmedicine.show();   
        }
    }//GEN-LAST:event_jList1FocusGained

    private void jList3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList3FocusGained
                String selection=String.valueOf(jList3.getSelectedValue());
        
        if("Electrical Items".equals(selection)){
               FrontDesktopPane3.removeAll();
               DeleteElectricGoods delete=new DeleteElectricGoods(this.FrontDesktopPane3);
               FrontDesktopPane3.add(delete);
               delete.show();
        }else if("Furniture".equals(selection)){
            FrontDesktopPane3.removeAll();
            DeleteFurniture deletefur=new DeleteFurniture(this.FrontDesktopPane3);
            FrontDesktopPane3.add(deletefur);
            deletefur.show(); 
        }else if("Books".equals(selection)){
            FrontDesktopPane3.removeAll();
            DeleteBook deletebook=new DeleteBook(this.FrontDesktopPane3);
            FrontDesktopPane3.add(deletebook);
            deletebook.show();
        }else if("Tools".equals(selection)){
            FrontDesktopPane3.removeAll();
            DeleteTool deletetool=new DeleteTool(this.FrontDesktopPane3);
            FrontDesktopPane3.add(deletetool);
            deletetool.show();
        }else if("Garments Or Accessories".equals(selection)){
            FrontDesktopPane3.removeAll();
            DeleteGarmentAndAccesory deletegaa=new DeleteGarmentAndAccesory(this.FrontDesktopPane3);
           FrontDesktopPane3.add(deletegaa);
            deletegaa.show(); 
        }else if("Other items".equals(selection)){
            FrontDesktopPane3.removeAll();
            DeleteOtherItem deleteother=new DeleteOtherItem(this.FrontDesktopPane3);
            FrontDesktopPane3.add(deleteother);
            deleteother.show(); 
        }else if("Repairs".equals(selection)){
            FrontDesktopPane3.removeAll();
            DeleteRepair deleterepair=new DeleteRepair(this.FrontDesktopPane3);
            FrontDesktopPane3.add(deleterepair);
            deleterepair.show();         
        }else if("Medicine".equals(selection)){
            FrontDesktopPane3.removeAll();
            DeleteMedicine addNewmedicine=new DeleteMedicine(this.FrontDesktopPane3);
            FrontDesktopPane3.add(addNewmedicine);
            addNewmedicine.show();   
        }
    }//GEN-LAST:event_jList3FocusGained

    private void jList4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList4FocusGained
        String selection=String.valueOf(jList4.getSelectedValue());
        
        if("Electrical Items".equals(selection)){
               FrontDesktopPane4.removeAll();
               SearchElectricGoods search=new SearchElectricGoods(this.FrontDesktopPane4);
               FrontDesktopPane4.add(search);
               search.show();
        }else if("Furniture".equals(selection)){
            FrontDesktopPane4.removeAll();
            SearchFurniture addNewfur=new SearchFurniture(this.FrontDesktopPane4);
            FrontDesktopPane4.add(addNewfur);
            addNewfur.show(); 
        }else if("Books".equals(selection)){
            FrontDesktopPane4.removeAll();
            SearchBook addNewbook=new SearchBook(this.FrontDesktopPane4);
            FrontDesktopPane4.add(addNewbook);
            addNewbook.show();
        }else if("Tools".equals(selection)){
            FrontDesktopPane4.removeAll();
            SearchTool addNewtool=new SearchTool(this.FrontDesktopPane4);
            FrontDesktopPane4.add(addNewtool);
            addNewtool.show();
        }else if("Garments Or Accessories".equals(selection)){
            FrontDesktopPane4.removeAll();
            SearchGarmentAndAccesory searchGaa=new SearchGarmentAndAccesory(this.FrontDesktopPane4);
           FrontDesktopPane4.add(searchGaa);
            searchGaa.show(); 
        }else if("Other items".equals(selection)){
            FrontDesktopPane4.removeAll();
            SearchOtherItem searchOther=new SearchOtherItem(this.FrontDesktopPane4);
           FrontDesktopPane4.add(searchOther);
            searchOther.show(); 
        }else if("Repairs".equals(selection)){
            FrontDesktopPane4.removeAll();
            SearchRepair seachRepair=new SearchRepair(this.FrontDesktopPane4);
            FrontDesktopPane4.add(seachRepair);
            seachRepair.show();         
        }else if("Medicine".equals(selection)){
            FrontDesktopPane4.removeAll();
            SearchMedicine searchMedicine=new SearchMedicine(this.FrontDesktopPane4);
            FrontDesktopPane4.add(searchMedicine);
            searchMedicine.show();   
        }
    }//GEN-LAST:event_jList4FocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane FrontDesktopPane1;
    private javax.swing.JDesktopPane FrontDesktopPane2;
    private javax.swing.JDesktopPane FrontDesktopPane3;
    private javax.swing.JDesktopPane FrontDesktopPane4;
    private javax.swing.JTextField addSearchText;
    private javax.swing.JTextField deleteSearchText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField searchText;
    private javax.swing.JTextField updateSearchText;
    // End of variables declaration//GEN-END:variables
}
