/*
 * Copyright (c) 2016 SLIIT, All Rights Reserved.
 * HOME MANAGEMENT SYSTEM
 * SEP GROUP PROJECT - 3rd YEAR
 *
 */
package view.finance;

import model.finance.Cashexpenses;
import controller.finance.CashExpensesController;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author user
 */
public class CashExpenses extends javax.swing.JInternalFrame {

    /**
     * Creates new form CashExpenses
     */
    public CashExpenses() {
        initComponents();
        
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        displaytable();
    }
           
    /**
     * Load table
     */
    public static void displaytable(){
  
    	jTableNewCashExpenseDetails.setModel(CashExpensesController.LoadCashExpenseTable());
    }
    
    /**
     * Load search results in table
     */
    public static void displaySearch(){
          
          Date dsearch = jDateChooserNewCashExpenseSearch.getDate();
        
          //If user didn't select a group from the group combo box.
          if(dsearch.equals("")){    
              
              displaytable();      
          }
             
          //If user selects a group from the group combo box.
          else{
              
              jTableNewCashExpenseDetails.setModel(CashExpensesController.displaySearchedCashExpenseTable(dsearch)); 
              
          }
      }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableNewCashExpenseDetails = new javax.swing.JTable();
        jButtonNewCashExpenseDelete = new javax.swing.JButton();
        jButtonNewCashExpenseUpdate = new javax.swing.JButton();
        jButtonNewCashExpenseRefresh = new javax.swing.JButton();
        jButtonNewCashExpenseSearch = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jDateChooserNewCashExpenseSearch = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNewCashExpenseAmount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNewCashExpenseReason = new javax.swing.JTextArea();
        jButtonNewCashExpenseClear = new javax.swing.JButton();
        jButtonNewCashExpenseAdd = new javax.swing.JButton();
        jDateChooseNewCashExpenseDate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxNewCashExpenseCategory = new javax.swing.JComboBox();
        jLabel58 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1245, 590));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(156, 190, 234));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableNewCashExpenseDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableNewCashExpenseDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNewCashExpenseDetailsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableNewCashExpenseDetails);

        jButtonNewCashExpenseDelete.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNewCashExpenseDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNewCashExpenseDelete.setForeground(new java.awt.Color(255, 0, 0));
        jButtonNewCashExpenseDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finance/deleteRed.png"))); // NOI18N
        jButtonNewCashExpenseDelete.setText("REMOVE");
        jButtonNewCashExpenseDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewCashExpenseDeleteActionPerformed(evt);
            }
        });

        jButtonNewCashExpenseUpdate.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNewCashExpenseUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNewCashExpenseUpdate.setForeground(new java.awt.Color(255, 204, 0));
        jButtonNewCashExpenseUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finance/updateYelllow.png"))); // NOI18N
        jButtonNewCashExpenseUpdate.setText("UPDATE");
        jButtonNewCashExpenseUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewCashExpenseUpdateActionPerformed(evt);
            }
        });

        jButtonNewCashExpenseRefresh.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNewCashExpenseRefresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNewCashExpenseRefresh.setForeground(new java.awt.Color(0, 153, 0));
        jButtonNewCashExpenseRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finance/Refresh-48 (1).png"))); // NOI18N
        jButtonNewCashExpenseRefresh.setText("REFRESH");
        jButtonNewCashExpenseRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewCashExpenseRefreshActionPerformed(evt);
            }
        });

        jButtonNewCashExpenseSearch.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNewCashExpenseSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNewCashExpenseSearch.setForeground(new java.awt.Color(255, 102, 0));
        jButtonNewCashExpenseSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finance/Search-48 (1).png"))); // NOI18N
        jButtonNewCashExpenseSearch.setText("SEARCH");
        jButtonNewCashExpenseSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewCashExpenseSearchActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Date");

        jDateChooserNewCashExpenseSearch.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooserNewCashExpenseSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNewCashExpenseSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonNewCashExpenseRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonNewCashExpenseUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButtonNewCashExpenseDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewCashExpenseRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewCashExpenseSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jDateChooserNewCashExpenseSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewCashExpenseUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewCashExpenseDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(156, 190, 234));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Reason for Expense");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Date");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Amount");

        jTextFieldNewCashExpenseAmount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTextAreaNewCashExpenseReason.setColumns(20);
        jTextAreaNewCashExpenseReason.setRows(5);
        jTextAreaNewCashExpenseReason.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPane1.setViewportView(jTextAreaNewCashExpenseReason);

        jButtonNewCashExpenseClear.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNewCashExpenseClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNewCashExpenseClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finance/Broom-48.png"))); // NOI18N
        jButtonNewCashExpenseClear.setText("CLEAR");
        jButtonNewCashExpenseClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewCashExpenseClearActionPerformed(evt);
            }
        });

        jButtonNewCashExpenseAdd.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNewCashExpenseAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNewCashExpenseAdd.setForeground(new java.awt.Color(0, 0, 153));
        jButtonNewCashExpenseAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finance/addBlue.png"))); // NOI18N
        jButtonNewCashExpenseAdd.setText("ADD");
        jButtonNewCashExpenseAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewCashExpenseAddActionPerformed(evt);
            }
        });

        jDateChooseNewCashExpenseDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jDateChooseNewCashExpenseDate.setDateFormatString("yyyy-MM-dd");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Expense Category");

        jComboBoxNewCashExpenseCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Category", "Vehicle", "Food", "Education", "Furniture", "Electric Goods", "Transport", "Accessary", "Clothing", "Health", "Kitchen Goods", "Other" }));
        jComboBoxNewCashExpenseCategory.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jComboBoxNewCashExpenseCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNewCashExpenseCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxNewCashExpenseCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNewCashExpenseClear, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonNewCashExpenseAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldNewCashExpenseAmount, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jDateChooseNewCashExpenseDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxNewCashExpenseCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooseNewCashExpenseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldNewCashExpenseAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewCashExpenseClear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewCashExpenseAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        jLabel58.setBackground(new java.awt.Color(204, 204, 204));
        jLabel58.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(102, 0, 102));
        jLabel58.setText("                     Add New Expense Details");
        jLabel58.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(102, 0, 102)));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 102));
        jLabel10.setText("                                                                  Cash Expense Detail List");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(102, 0, 102)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewCashExpenseUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewCashExpenseUpdateActionPerformed

        int response = JOptionPane.showConfirmDialog(null, "Do you really want to update?", "Confirm",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            
       
        int i = jTableNewCashExpenseDetails.getSelectedRow();
        String ID = jTableNewCashExpenseDetails.getValueAt(i, 0).toString();

        String expenseCategory;    //cash expense category type
        String reason;             //reason for the cash payment
        Date date;                 //date of payment
        String amount;             //amount paid

        expenseCategory = jComboBoxNewCashExpenseCategory.getSelectedItem().toString();
        reason = jTextAreaNewCashExpenseReason.getText();
        date = jDateChooseNewCashExpenseDate.getDate();
        amount = jTextFieldNewCashExpenseAmount.getText();
               
        Cashexpenses cash = new Cashexpenses();
        cash.setCashExpenseId(Integer.parseInt(ID));
        cash.setExpenseCategory(expenseCategory);
        cash.setReason(reason);
        cash.setDate(date);
        cash.setAmount(amount);
       
        CashExpensesController.updateCashExpense(cash);
        
        displaytable();
                           
      }
    }//GEN-LAST:event_jButtonNewCashExpenseUpdateActionPerformed

    private void jButtonNewCashExpenseRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewCashExpenseRefreshActionPerformed
        //load table
        displaytable();   
    }//GEN-LAST:event_jButtonNewCashExpenseRefreshActionPerformed

    private void jButtonNewCashExpenseSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewCashExpenseSearchActionPerformed
      //load search results in table
        displaySearch();
    }//GEN-LAST:event_jButtonNewCashExpenseSearchActionPerformed

    private void jButtonNewCashExpenseClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewCashExpenseClearActionPerformed
        //clear text boxes
        jComboBoxNewCashExpenseCategory.setSelectedItem("Select Category");
        jTextAreaNewCashExpenseReason.setText("");
        ((JTextField)jDateChooseNewCashExpenseDate.getDateEditor().getUiComponent()).setText("");
        jTextFieldNewCashExpenseAmount.setText("");
    }//GEN-LAST:event_jButtonNewCashExpenseClearActionPerformed

    private void jButtonNewCashExpenseAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewCashExpenseAddActionPerformed

        try{
            String expenseCategory;    //cash expense category type
            String reason;             //reason for the cash payment
            Date date;                 //date of payment
            String amount;             //amount paid
            
            
            expenseCategory = jComboBoxNewCashExpenseCategory.getSelectedItem().toString();
            reason = jTextAreaNewCashExpenseReason.getText();
            date = jDateChooseNewCashExpenseDate.getDate();
            amount = jTextFieldNewCashExpenseAmount.getText();
            
          
            Cashexpenses newCash = new Cashexpenses();
            newCash.setExpenseCategory(expenseCategory);
            newCash.setReason(reason);
            newCash.setDate(date);
            newCash.setAmount(amount);
            
           
            CashExpensesController.addCashExpense(newCash);
        }

        catch(Exception e){

            JOptionPane.showMessageDialog(null, e);
        }
              
        displaytable();
        
        jComboBoxNewCashExpenseCategory.setSelectedItem("Select Category");
        jTextAreaNewCashExpenseReason.setText("");
        ((JTextField)jDateChooseNewCashExpenseDate.getDateEditor().getUiComponent()).setText("");
        jTextFieldNewCashExpenseAmount.setText("");
    }//GEN-LAST:event_jButtonNewCashExpenseAddActionPerformed

    private void jButtonNewCashExpenseDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewCashExpenseDeleteActionPerformed
        //delete cash expenses
        int response = JOptionPane.showConfirmDialog(null, "Do you really want to delete?", "Confirm",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {

            int i = jTableNewCashExpenseDetails.getSelectedRow();
            CashExpensesController.DeleteCashExpense(jTableNewCashExpenseDetails.getValueAt(i, 0).toString());
            displaytable();

        }
    }//GEN-LAST:event_jButtonNewCashExpenseDeleteActionPerformed

    private void jComboBoxNewCashExpenseCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNewCashExpenseCategoryActionPerformed

    }//GEN-LAST:event_jComboBoxNewCashExpenseCategoryActionPerformed

    private void jTableNewCashExpenseDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNewCashExpenseDetailsMouseClicked
        
         int i = jTableNewCashExpenseDetails.getSelectedRow();

        jComboBoxNewCashExpenseCategory.setSelectedItem(jTableNewCashExpenseDetails.getValueAt(i, 1).toString());          
        jTextAreaNewCashExpenseReason.setText(jTableNewCashExpenseDetails.getValueAt(i, 2).toString());
        ((JTextField)jDateChooseNewCashExpenseDate.getDateEditor().getUiComponent()).setText(jTableNewCashExpenseDetails.getValueAt(i, 3).toString());
        jTextFieldNewCashExpenseAmount.setText(jTableNewCashExpenseDetails.getValueAt(i, 4).toString());
    }//GEN-LAST:event_jTableNewCashExpenseDetailsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNewCashExpenseAdd;
    private javax.swing.JButton jButtonNewCashExpenseClear;
    private javax.swing.JButton jButtonNewCashExpenseDelete;
    private javax.swing.JButton jButtonNewCashExpenseRefresh;
    private javax.swing.JButton jButtonNewCashExpenseSearch;
    private javax.swing.JButton jButtonNewCashExpenseUpdate;
    private static javax.swing.JComboBox jComboBoxNewCashExpenseCategory;
    private com.toedter.calendar.JDateChooser jDateChooseNewCashExpenseDate;
    private static com.toedter.calendar.JDateChooser jDateChooserNewCashExpenseSearch;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable jTableNewCashExpenseDetails;
    private javax.swing.JTextArea jTextAreaNewCashExpenseReason;
    private javax.swing.JTextField jTextFieldNewCashExpenseAmount;
    // End of variables declaration//GEN-END:variables
}
