/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.finance;

import controller.finance.CreditCardPaymentsController;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.finance.Creditcardpayments;


/**
 *
 * @author Administrator
 */
public class CreditCardPayments extends javax.swing.JInternalFrame {

    /**
     * Creates new form RemainingPayments
     */
    public CreditCardPayments() {
        initComponents();
        
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        loadcombo();
        displaytable();
    }
    
     /**
     * Load combo box
     */
    public static void loadcombo(){
    	List l = CreditCardPaymentsController.LoadcomboList();
               
        for(Object o : l) {
            jComboBoxCreditCardPaymentSearch.addItem(o);
        }        
    }  
    
     /**
     * Load table data
     */
    public static void displaytable(){
  
    	jTableCreditCardPayments.setModel(CreditCardPaymentsController.LoadCreditCardPaymentTable());
        HideColumns();
    }
    
     /**
     * Load search result
     */
    public static void displaySearch(){
          
          String searchCreditCard = jComboBoxCreditCardPaymentSearch.getSelectedItem().toString();
        
          //If user didn't select a group from the group combo box.
          if(searchCreditCard.equals("Select Credit Card No")){    
              
              displaytable();      
          }
             
          //If user selects a group from the group combo box.
          else{
              
              jTableCreditCardPayments.setModel(CreditCardPaymentsController.displaySearchedCreditCardPaymentsTable(searchCreditCard)); 
              HideColumns();
          }
      }
    
    /**
     * Hide ID column in table 
     */
    public static void HideColumns(){
        
            int i = 0;
            jTableCreditCardPayments.getColumnModel().getColumn(i).setWidth(0);
            jTableCreditCardPayments.getColumnModel().getColumn(i).setMinWidth(0);
            jTableCreditCardPayments.getColumnModel().getColumn(i).setMaxWidth(0);
                  
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox();
        jLabelCreditCardNo = new javax.swing.JLabel();
        jLabelRemainingPaymentAmount = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jTextFieldSettledPaymentAmount = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jLabelRemainingBalance = new javax.swing.JLabel();
        jButtonNewCreditCardPaymentUpdate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCreditCardPayments = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxCreditCardPaymentSearch = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jButtonNewCreditCardPaymentSearch = new javax.swing.JButton();
        jButtonNewCreditCardPaymentRefresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1245, 590));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel57.setBackground(new java.awt.Color(204, 204, 204));
        jLabel57.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(102, 0, 102));
        jLabel57.setText("       Edit Credit Card Payment Details");
        jLabel57.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(102, 0, 102)));

        jPanel13.setBackground(new java.awt.Color(156, 190, 234));
        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel13.setMinimumSize(new java.awt.Dimension(486, 374));

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel64.setText("Credit Card No");

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel65.setText("Remaining Payment Amount");

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel66.setText("Status");

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Remaining", "Settled" }));
        jComboBoxStatus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 1, true));

        jLabelCreditCardNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabelRemainingPaymentAmount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel67.setText("Settled Payment Amount");

        jTextFieldSettledPaymentAmount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel68.setText("Remaining Balance");

        jLabelRemainingBalance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jButtonNewCreditCardPaymentUpdate.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNewCreditCardPaymentUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNewCreditCardPaymentUpdate.setForeground(new java.awt.Color(255, 204, 0));
        jButtonNewCreditCardPaymentUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finance/updateYelllow.png"))); // NOI18N
        jButtonNewCreditCardPaymentUpdate.setText("UPDATE");
        jButtonNewCreditCardPaymentUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewCreditCardPaymentUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel68)
                            .addComponent(jLabel67)
                            .addComponent(jLabelRemainingPaymentAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel65)
                            .addComponent(jLabel66)
                            .addComponent(jComboBoxStatus, 0, 224, Short.MAX_VALUE)
                            .addComponent(jTextFieldSettledPaymentAmount)
                            .addComponent(jLabelCreditCardNo, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(jLabel64)
                            .addComponent(jLabelRemainingBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButtonNewCreditCardPaymentUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel64)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCreditCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel68)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRemainingBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel65)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRemainingPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel67)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSettledPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel66)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButtonNewCreditCardPaymentUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(156, 190, 234));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setPreferredSize(new java.awt.Dimension(619, 374));

        jTableCreditCardPayments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCreditCardPayments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCreditCardPaymentsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCreditCardPayments);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Credit Card No");

        jComboBoxCreditCardPaymentSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Credit Card No" }));

        jLabel9.setText("Select relevant record row to edit details.");

        jButtonNewCreditCardPaymentSearch.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNewCreditCardPaymentSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNewCreditCardPaymentSearch.setForeground(new java.awt.Color(255, 153, 0));
        jButtonNewCreditCardPaymentSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finance/Search-48 (1).png"))); // NOI18N
        jButtonNewCreditCardPaymentSearch.setText("SEARCH");
        jButtonNewCreditCardPaymentSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewCreditCardPaymentSearchActionPerformed(evt);
            }
        });

        jButtonNewCreditCardPaymentRefresh.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNewCreditCardPaymentRefresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNewCreditCardPaymentRefresh.setForeground(new java.awt.Color(0, 153, 0));
        jButtonNewCreditCardPaymentRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finance/Refresh-48 (1).png"))); // NOI18N
        jButtonNewCreditCardPaymentRefresh.setText("REFRESH");
        jButtonNewCreditCardPaymentRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewCreditCardPaymentRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxCreditCardPaymentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNewCreditCardPaymentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNewCreditCardPaymentRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCreditCardPaymentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonNewCreditCardPaymentSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewCreditCardPaymentRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("                                                                     Credit Card Payment Details");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(102, 0, 102)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewCreditCardPaymentUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewCreditCardPaymentUpdateActionPerformed

        //update credit card payment data
        int response = JOptionPane.showConfirmDialog(null, "Do you really want to update?", "Confirm",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {

            int i = jTableCreditCardPayments.getSelectedRow();
            String ID = jTableCreditCardPayments.getValueAt(i, 0).toString();

            String cardNo;              //credit card number
            String remainingBalance;    //credit card remaning balance
            String remainingPayment;    //remaining payment of card
            String settledPayment;        //settled payment of card
            String status;              //status of card
            
            cardNo = jLabelCreditCardNo.getText();
            remainingBalance = jLabelRemainingBalance.getText();
            remainingPayment = jLabelRemainingPaymentAmount.getText();
            settledPayment = jTextFieldSettledPaymentAmount.getText();
            status = jComboBoxStatus.getSelectedItem().toString();
            
            if(cardNo.equals(jTableCreditCardPayments.getValueAt(i, 1).toString()))
            {
                Creditcardpayments crdtcard = new Creditcardpayments();
                
                List p = CreditCardPaymentsController.LoadCardPayment(cardNo);
                
                 for(Object t : p) {
                
                    model.finance.Creditcardpayments crdtcards = (model.finance.Creditcardpayments)t;
                      
                    String settlePay = crdtcards.getSettledPayments();
                                
                    int setlPay = Integer.parseInt(settlePay);
                    int setlAmt = Integer.parseInt(settledPayment);
                        
                    int tot = setlPay + setlAmt;
                    String totS = String.valueOf(tot);
                         
                    String totalPay = (totS);
                                    
                    crdtcard.setPaymentId(Integer.parseInt(ID));
                    crdtcard.setCardNo(cardNo);
                    crdtcard.setRemainingBalance(remainingBalance);
                    crdtcard.setRemainingPayments(remainingPayment);
                    crdtcard.setSettledPayments(totalPay);
                
                    if((jTableCreditCardPayments.getValueAt(i, 3).toString()).equals(settledPayment))
                    {
                        crdtcard.setStatus("Settled");
                    }
                    if(!(jTableCreditCardPayments.getValueAt(i, 3).toString()).equals(settledPayment))
                    {                      
                        crdtcard.setStatus(status);                  
                    }
                
                }
                
                CreditCardPaymentsController.updateCreditCardPayment(crdtcard);

                displaytable();
            }

            else
            {
                JOptionPane.showMessageDialog(null, "Credit Card Number cannot be edited!! Please try to edit other details without card number!");
            }

        }
    }//GEN-LAST:event_jButtonNewCreditCardPaymentUpdateActionPerformed

    private void jButtonNewCreditCardPaymentSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewCreditCardPaymentSearchActionPerformed
        displaySearch();
    }//GEN-LAST:event_jButtonNewCreditCardPaymentSearchActionPerformed

    private void jButtonNewCreditCardPaymentRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewCreditCardPaymentRefreshActionPerformed
        displaytable();
    }//GEN-LAST:event_jButtonNewCreditCardPaymentRefreshActionPerformed

    private void jTableCreditCardPaymentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCreditCardPaymentsMouseClicked
        
         int i = jTableCreditCardPayments.getSelectedRow();

        jLabelCreditCardNo.setText(jTableCreditCardPayments.getValueAt(i, 1).toString());
        jLabelRemainingBalance.setText(jTableCreditCardPayments.getValueAt(i, 2).toString());
        jLabelRemainingPaymentAmount.setText(jTableCreditCardPayments.getValueAt(i, 3).toString());
        jTextFieldSettledPaymentAmount.setText(jTableCreditCardPayments.getValueAt(i, 4).toString());
        jComboBoxStatus.setSelectedItem(jTableCreditCardPayments.getValueAt(i, 5).toString());
      
    }//GEN-LAST:event_jTableCreditCardPaymentsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNewCreditCardPaymentRefresh;
    private javax.swing.JButton jButtonNewCreditCardPaymentSearch;
    private javax.swing.JButton jButtonNewCreditCardPaymentUpdate;
    private static javax.swing.JComboBox jComboBoxCreditCardPaymentSearch;
    private javax.swing.JComboBox jComboBoxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCreditCardNo;
    private javax.swing.JLabel jLabelRemainingBalance;
    private javax.swing.JLabel jLabelRemainingPaymentAmount;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable jTableCreditCardPayments;
    private javax.swing.JTextField jTextFieldSettledPaymentAmount;
    // End of variables declaration//GEN-END:variables
}
