/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.finance;

import model.finance.Creditcardexpenses;
import controller.finance.CreditCardExpensesController;
import controller.finance.CreditCardPaymentsController;
import controller.finance.CreditCardsController;
import java.sql.ResultSet;
import static java.util.Collections.list;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.finance.Creditcardpayments;
import model.finance.Creditcards;

/**
 *
 * @author user
 */
public class CreditCardExpenses extends javax.swing.JInternalFrame {

    /**
     * Creates new form CreditCardExpenses
     */
    public CreditCardExpenses() {
        initComponents();
        
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        loadcombo();
        loadcombo1();
        displaytable(); 
    }
    
    /**
     * Load combo box
     */
    public static void loadcombo(){
    	List l = CreditCardExpensesController.LoadcomboList();
               
        for(Object o : l) {
            jComboBoxNewCreditCardExpenseSearch.addItem(o);
        }        
    }   
    
    /**
     * Load combo box
     */
    public static void loadcombo1(){
    	List l = CreditCardExpensesController.LoadcomboList();
               
        for(Object o : l) {
            jComboBoxNewCreditCardExpenseCardNo.addItem(o);
        }        
    }   
    
    /**
     * Load table
     */
     public static void displaytable(){
  
    	jTableNewCreditCardExpenseDetails.setModel(CreditCardExpensesController.LoadCreditCardExpenseTable());
    }
    
     /**
     * Load search results in table
     */
    public static void displaySearch(){
          
          String dsearch = jComboBoxNewCreditCardExpenseSearch.getSelectedItem().toString();
        
          //If user didn't select a group from the group combo box.
          if(dsearch.equals("Select Credit Card No")){    
              
              displaytable();      
          }
             
          //If user selects a group from the group combo box.
          else{
              
              jTableNewCreditCardExpenseDetails.setModel(CreditCardExpensesController.displaySearchedCreditCardExpenseTable(dsearch)); 
             
          }
      }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableNewCreditCardExpenseDetails = new javax.swing.JTable();
        jButtonNewCreditCardExpenseDelete = new javax.swing.JButton();
        jButtonNewCreditCardExpenseUpdate = new javax.swing.JButton();
        jButtonNewCreditCardExpenseRefresh = new javax.swing.JButton();
        jButtonNewCreditCardExpenseSearch = new javax.swing.JButton();
        jComboBoxNewCreditCardExpenseSearch = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxNewCreditCardExpenseCardNo = new javax.swing.JComboBox();
        jTextFieldNewCreditCardExpenseAmount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNewCreditCardExpenseReason = new javax.swing.JTextArea();
        jButtonNewCreditCardExpenseClear = new javax.swing.JButton();
        jButtonNewCreditCardExpenseAdd = new javax.swing.JButton();
        jDateChooseNewCreditCardExpenseDate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxNewCreditCardExpenseCategory = new javax.swing.JComboBox();
        jLabel58 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1245, 590));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1245, 590));

        jPanel2.setBackground(new java.awt.Color(156, 190, 234));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableNewCreditCardExpenseDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableNewCreditCardExpenseDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNewCreditCardExpenseDetailsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableNewCreditCardExpenseDetails);

        jButtonNewCreditCardExpenseDelete.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNewCreditCardExpenseDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNewCreditCardExpenseDelete.setForeground(new java.awt.Color(255, 0, 0));
        jButtonNewCreditCardExpenseDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finance/deleteRed.png"))); // NOI18N
        jButtonNewCreditCardExpenseDelete.setText("REMOVE");
        jButtonNewCreditCardExpenseDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewCreditCardExpenseDeleteActionPerformed(evt);
            }
        });

        jButtonNewCreditCardExpenseUpdate.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNewCreditCardExpenseUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNewCreditCardExpenseUpdate.setForeground(new java.awt.Color(255, 204, 0));
        jButtonNewCreditCardExpenseUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finance/updateYelllow.png"))); // NOI18N
        jButtonNewCreditCardExpenseUpdate.setText("UPDATE");
        jButtonNewCreditCardExpenseUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewCreditCardExpenseUpdateActionPerformed(evt);
            }
        });

        jButtonNewCreditCardExpenseRefresh.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNewCreditCardExpenseRefresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNewCreditCardExpenseRefresh.setForeground(new java.awt.Color(0, 153, 0));
        jButtonNewCreditCardExpenseRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finance/Refresh-48 (1).png"))); // NOI18N
        jButtonNewCreditCardExpenseRefresh.setText("REFRESH");
        jButtonNewCreditCardExpenseRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewCreditCardExpenseRefreshActionPerformed(evt);
            }
        });

        jButtonNewCreditCardExpenseSearch.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNewCreditCardExpenseSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNewCreditCardExpenseSearch.setForeground(new java.awt.Color(255, 153, 0));
        jButtonNewCreditCardExpenseSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finance/Search-48 (1).png"))); // NOI18N
        jButtonNewCreditCardExpenseSearch.setText("SEARCH");
        jButtonNewCreditCardExpenseSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewCreditCardExpenseSearchActionPerformed(evt);
            }
        });

        jComboBoxNewCreditCardExpenseSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Credit card No" }));
        jComboBoxNewCreditCardExpenseSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNewCreditCardExpenseSearchActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Credit Card No");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxNewCreditCardExpenseSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonNewCreditCardExpenseSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonNewCreditCardExpenseRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonNewCreditCardExpenseUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButtonNewCreditCardExpenseDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewCreditCardExpenseRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewCreditCardExpenseSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxNewCreditCardExpenseSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewCreditCardExpenseUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewCreditCardExpenseDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel1.setBackground(new java.awt.Color(156, 190, 234));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Credit card No");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Reason");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Date");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Amount");

        jComboBoxNewCreditCardExpenseCardNo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Credit Card No", " " }));
        jComboBoxNewCreditCardExpenseCardNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jComboBoxNewCreditCardExpenseCardNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNewCreditCardExpenseCardNoActionPerformed(evt);
            }
        });

        jTextFieldNewCreditCardExpenseAmount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTextAreaNewCreditCardExpenseReason.setColumns(20);
        jTextAreaNewCreditCardExpenseReason.setRows(5);
        jTextAreaNewCreditCardExpenseReason.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPane1.setViewportView(jTextAreaNewCreditCardExpenseReason);

        jButtonNewCreditCardExpenseClear.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNewCreditCardExpenseClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNewCreditCardExpenseClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finance/Broom-48.png"))); // NOI18N
        jButtonNewCreditCardExpenseClear.setText("CLEAR");
        jButtonNewCreditCardExpenseClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewCreditCardExpenseClearActionPerformed(evt);
            }
        });

        jButtonNewCreditCardExpenseAdd.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNewCreditCardExpenseAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNewCreditCardExpenseAdd.setForeground(new java.awt.Color(0, 0, 204));
        jButtonNewCreditCardExpenseAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finance/addBlue.png"))); // NOI18N
        jButtonNewCreditCardExpenseAdd.setText("ADD");
        jButtonNewCreditCardExpenseAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewCreditCardExpenseAddActionPerformed(evt);
            }
        });

        jDateChooseNewCreditCardExpenseDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jDateChooseNewCreditCardExpenseDate.setDateFormatString("yyyy-MM-dd");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Expense Category");

        jComboBoxNewCreditCardExpenseCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Category", "Vehicle", "Food", "Education", "Furniture", "Electric Goods", "Transport", "Accessary", "Clothing", "Health", "Kitchen Goods", "Other", " " }));
        jComboBoxNewCreditCardExpenseCategory.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jComboBoxNewCreditCardExpenseCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNewCreditCardExpenseCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNewCreditCardExpenseClear, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonNewCreditCardExpenseAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldNewCreditCardExpenseAmount, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jDateChooseNewCreditCardExpenseDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBoxNewCreditCardExpenseCardNo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxNewCreditCardExpenseCategory, javax.swing.GroupLayout.Alignment.LEADING, 0, 192, Short.MAX_VALUE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxNewCreditCardExpenseCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxNewCreditCardExpenseCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooseNewCreditCardExpenseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldNewCreditCardExpenseAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewCreditCardExpenseClear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewCreditCardExpenseAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        jLabel58.setBackground(new java.awt.Color(204, 204, 204));
        jLabel58.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(102, 0, 102));
        jLabel58.setText("                     Add New Expense Details");
        jLabel58.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(102, 0, 102)));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 102));
        jLabel10.setText("                                                         Credit Card Expense Detail List");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(102, 0, 102)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1303, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewCreditCardExpenseUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewCreditCardExpenseUpdateActionPerformed

        int response = JOptionPane.showConfirmDialog(null, "Do you really want to update?", "Confirm",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
          
      
        int i = jTableNewCreditCardExpenseDetails.getSelectedRow();
        String ID = jTableNewCreditCardExpenseDetails.getValueAt(i, 0).toString();

        String creditCardNo;    //credit card no that did the payment
        String expenseCategory; //credit card expense category type
        String reason;          //reason for the payment
        Date date;              //date of payment
        String amount;          //payment amount

        creditCardNo = jComboBoxNewCreditCardExpenseCardNo.getSelectedItem().toString();
        expenseCategory = jComboBoxNewCreditCardExpenseCategory.getSelectedItem().toString();
        reason = jTextAreaNewCreditCardExpenseReason.getText();
        date = jDateChooseNewCreditCardExpenseDate.getDate();
        amount = jTextFieldNewCreditCardExpenseAmount.getText();
                   
        if(creditCardNo.equals(jTableNewCreditCardExpenseDetails.getValueAt(i, 1).toString()))
        { 
            Creditcardexpenses credit = new Creditcardexpenses();
            credit.setCardExpenseId(Integer.parseInt(ID));
            credit.setCardNo(creditCardNo);
            credit.setExpenseCategory(expenseCategory);
            credit.setReason(reason);
            credit.setDate(date);
            credit.setAmount(amount);
       
            CreditCardExpensesController.updateCreditCardExpense(credit);
            
            Creditcardpayments cp = new Creditcardpayments();
            
            long count = CreditCardsController.CountCardNo(creditCardNo);
            
            if(count > 0){
                
                List l = CreditCardsController.LoadCardNo(creditCardNo);
                
                List p = CreditCardPaymentsController.LoadCardPayment(creditCardNo);
            
                for(Object o : l) {
                
                    model.finance.Creditcards crdtcard = (model.finance.Creditcards)o;
                    
                    String cardNo = crdtcard.getCardNo();
                    String cardType = crdtcard.getCardType();
                    
                    for(Object t : p) {
                
                        model.finance.Creditcardpayments crdtcards = (model.finance.Creditcardpayments)t;
                        
                        String payId = crdtcards.getPaymentId().toString();
                        String remaningBal = crdtcards.getRemainingBalance();
                        String remainingPay = crdtcards.getRemainingPayments();
                        String settlePay = crdtcards.getSettledPayments();
                                            
                    
                        int balance = Integer.parseInt(remaningBal) - Integer.parseInt(amount);
                        
                        String bal = String.valueOf(balance);
                        
                        int remPay = Integer.parseInt(remainingPay);
                        int amt = Integer.parseInt(amount);
                        
                        int tot = remPay + amt;
                        String totS = String.valueOf(tot);
                         
                        String totalPay = (totS);
                        
                                          
                        cp.setPaymentId(Integer.parseInt(payId));
                        cp.setCardNo(cardNo);
                        cp.setRemainingBalance(bal);
                        cp.setRemainingPayments(totalPay);
                        cp.setSettledPayments(settlePay);
                        
                        if(remainingPay.equals (settlePay))
                        {
                           cp.setStatus("Settled");
                        }
                        if(!remainingPay.equals (settlePay))
                        {
                            cp.setStatus("Remaining");
                        }
                                                
                    }
                                       
                    CreditCardPaymentsController.updateCreditCardPayment(cp);
                    
                              
                }     
            
            }

            displaytable();
        }
        
        else 
        {
            JOptionPane.showMessageDialog(null, "Credit Card Number cannot be edited!! Please try to edit other details without credit card number!");
        }
       }
    }//GEN-LAST:event_jButtonNewCreditCardExpenseUpdateActionPerformed

    private void jButtonNewCreditCardExpenseRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewCreditCardExpenseRefreshActionPerformed
         displaytable();
    }//GEN-LAST:event_jButtonNewCreditCardExpenseRefreshActionPerformed

    private void jButtonNewCreditCardExpenseSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewCreditCardExpenseSearchActionPerformed
        displaySearch();
    }//GEN-LAST:event_jButtonNewCreditCardExpenseSearchActionPerformed

    private void jButtonNewCreditCardExpenseClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewCreditCardExpenseClearActionPerformed

        jComboBoxNewCreditCardExpenseCardNo.setSelectedItem("Select Credit Card No");
        jComboBoxNewCreditCardExpenseCategory.setSelectedItem("Select Category");
        jTextAreaNewCreditCardExpenseReason.setText("");
        ((JTextField)jDateChooseNewCreditCardExpenseDate.getDateEditor().getUiComponent()).setText("");
        jTextFieldNewCreditCardExpenseAmount.setText("");
    }//GEN-LAST:event_jButtonNewCreditCardExpenseClearActionPerformed

    private void jButtonNewCreditCardExpenseAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewCreditCardExpenseAddActionPerformed

        try{
            String creditCardNo;    //credit card no that did the payment
            String expenseCategory; //credit card expense category type
            String reason;          //reason for the payment
            Date date;              //date of payment
            String amount;          //payment amount

            creditCardNo = jComboBoxNewCreditCardExpenseCardNo.getSelectedItem().toString();
            expenseCategory = jComboBoxNewCreditCardExpenseCategory.getSelectedItem().toString();
            reason = jTextAreaNewCreditCardExpenseReason.getText();
            date = jDateChooseNewCreditCardExpenseDate.getDate();
            amount = jTextFieldNewCreditCardExpenseAmount.getText();

            Creditcardexpenses newCredit = new Creditcardexpenses();
            newCredit.setCardNo(creditCardNo);
            newCredit.setExpenseCategory(expenseCategory);
            newCredit.setReason(reason);
            newCredit.setDate(date);
            newCredit.setAmount(amount);

            CreditCardExpensesController.addCreditCardExpense(newCredit);
            
            Creditcardpayments cp = new Creditcardpayments();
            
            long count = CreditCardsController.CountCardNo(creditCardNo);
            
            if(count > 0){
                
                List l = CreditCardsController.LoadCardNo(creditCardNo);
                
                List p = CreditCardPaymentsController.LoadCardPayment(creditCardNo);
            
                for(Object o : l) {
                
                    model.finance.Creditcards crdtcard = (model.finance.Creditcards)o;
                    
                    String cardNo = crdtcard.getCardNo();
                    String cardType = crdtcard.getCardType();
                    
                    for(Object t : p) {
                
                        model.finance.Creditcardpayments crdtcards = (model.finance.Creditcardpayments)t;
                        
                        String payId = crdtcards.getPaymentId().toString();
                        String remaningBal = crdtcards.getRemainingBalance();
                        String remainingPay = crdtcards.getRemainingPayments();
                        String settlePay = crdtcards.getSettledPayments();
                                            
                    
                        int balance = Integer.parseInt(remaningBal) - Integer.parseInt(amount);
                        
                        String bal = String.valueOf(balance);
                        
                        int remPay = Integer.parseInt(remainingPay);
                        int amt = Integer.parseInt(amount);
                        
                        int tot = remPay + amt;
                        String totS = String.valueOf(tot);
                         
                        String totalPay = (totS);
                        
                                          
                        cp.setPaymentId(Integer.parseInt(payId));
                        cp.setCardNo(cardNo);
                        cp.setRemainingBalance(bal);
                        cp.setRemainingPayments(totalPay);
                        cp.setSettledPayments(settlePay);
                        
                        if(remainingPay.equals (settlePay))
                        {
                           cp.setStatus("Settled");
                        }
                        if(!remainingPay.equals (settlePay))
                        {
                           cp.setStatus("Remaining");
                        }
                       
                    }
                                       
                    CreditCardPaymentsController.updateCreditCardPayment(cp);
                    
                              
                }     
            
            }
            
        }
         
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e);
        }

        displaytable();
        
        jComboBoxNewCreditCardExpenseCardNo.setSelectedItem("Select Credit Card No");
        jComboBoxNewCreditCardExpenseCategory.setSelectedItem("Select Category");
        jTextAreaNewCreditCardExpenseReason.setText("");
        ((JTextField)jDateChooseNewCreditCardExpenseDate.getDateEditor().getUiComponent()).setText("");
        jTextFieldNewCreditCardExpenseAmount.setText("");
    }//GEN-LAST:event_jButtonNewCreditCardExpenseAddActionPerformed

    private void jButtonNewCreditCardExpenseDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewCreditCardExpenseDeleteActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Do you really want to delete?", "Confirm",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {

            int i = jTableNewCreditCardExpenseDetails.getSelectedRow();
            CreditCardExpensesController.DeleteCreditCardExpense(jTableNewCreditCardExpenseDetails.getValueAt(i, 0).toString());
            displaytable();

        }
    }//GEN-LAST:event_jButtonNewCreditCardExpenseDeleteActionPerformed

    private void jComboBoxNewCreditCardExpenseCardNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNewCreditCardExpenseCardNoActionPerformed
       
    }//GEN-LAST:event_jComboBoxNewCreditCardExpenseCardNoActionPerformed

    private void jComboBoxNewCreditCardExpenseSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNewCreditCardExpenseSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNewCreditCardExpenseSearchActionPerformed

    private void jComboBoxNewCreditCardExpenseCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNewCreditCardExpenseCategoryActionPerformed

    }//GEN-LAST:event_jComboBoxNewCreditCardExpenseCategoryActionPerformed

    private void jTableNewCreditCardExpenseDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNewCreditCardExpenseDetailsMouseClicked
        
        int i = jTableNewCreditCardExpenseDetails.getSelectedRow();

        jComboBoxNewCreditCardExpenseCardNo.setSelectedItem(jTableNewCreditCardExpenseDetails.getValueAt(i, 1).toString());
        jComboBoxNewCreditCardExpenseCategory.setSelectedItem(jTableNewCreditCardExpenseDetails.getValueAt(i, 2).toString());     
        jTextAreaNewCreditCardExpenseReason.setText(jTableNewCreditCardExpenseDetails.getValueAt(i, 3).toString());
        ((JTextField)jDateChooseNewCreditCardExpenseDate.getDateEditor().getUiComponent()).setText(jTableNewCreditCardExpenseDetails.getValueAt(i, 4).toString());
        jTextFieldNewCreditCardExpenseAmount.setText(jTableNewCreditCardExpenseDetails.getValueAt(i, 5).toString());
      
    }//GEN-LAST:event_jTableNewCreditCardExpenseDetailsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNewCreditCardExpenseAdd;
    private javax.swing.JButton jButtonNewCreditCardExpenseClear;
    private javax.swing.JButton jButtonNewCreditCardExpenseDelete;
    private javax.swing.JButton jButtonNewCreditCardExpenseRefresh;
    private javax.swing.JButton jButtonNewCreditCardExpenseSearch;
    private javax.swing.JButton jButtonNewCreditCardExpenseUpdate;
    public static javax.swing.JComboBox jComboBoxNewCreditCardExpenseCardNo;
    private static javax.swing.JComboBox jComboBoxNewCreditCardExpenseCategory;
    private static javax.swing.JComboBox jComboBoxNewCreditCardExpenseSearch;
    private com.toedter.calendar.JDateChooser jDateChooseNewCreditCardExpenseDate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable jTableNewCreditCardExpenseDetails;
    private javax.swing.JTextArea jTextAreaNewCreditCardExpenseReason;
    private javax.swing.JTextField jTextFieldNewCreditCardExpenseAmount;
    // End of variables declaration//GEN-END:variables
}
