/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.finance;

import model.finance.Salary;
import controller.finance.SalaryController;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author user
 */
public class UserSalary extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserSalary
     */
    public UserSalary() {
        initComponents();
        
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
       // loadcombo();
        displaytable();
    }
 
    /**
     * Load table data
     */
    public static void displaytable(){
       	
        jTableNewSalary.setModel(SalaryController.LoadSalaryTable());
            
    }
    
    /**
     * Load search result
     */
    public static void displaySearch(){
          
          String dsearch = jComboBoxNewSalarySearch.getSelectedItem().toString();
        
          //If user didn't select a group from the group combo box.
          if(dsearch.equals("Select Month")){    
              
              displaytable();      
          }
             
          //If user selects a group from the group combo box.
          else{
              
              jTableNewSalary.setModel(SalaryController.displaySearchedSalaryTable(dsearch)); 
             
          }
      }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTextBoxNewSalaryAmount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxNewSalaryMonth = new javax.swing.JComboBox();
        jButtonNewSalaryClear = new javax.swing.JButton();
        jButtonNewSalaryAdd = new javax.swing.JButton();
        jDateChooserNewSalaryReceivedDate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        JTextBoxNewSalaryBasicAmount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        JTextBoxNewSalaryOTAmount = new javax.swing.JTextField();
        JTextBoxNewSalaryHolderName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNewSalary = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxNewSalarySearch = new javax.swing.JComboBox();
        jButtonNewSalarySearch = new javax.swing.JButton();
        jButtonNewSalaryRefresh = new javax.swing.JButton();
        jButtonNewSalaryUpdate = new javax.swing.JButton();
        jButtonNewSalaryDelete = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1245, 640));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(156, 190, 234));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMinimumSize(new java.awt.Dimension(486, 374));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Month");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Salary Amount");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Salary Received Date");

        JTextBoxNewSalaryAmount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jComboBoxNewSalaryMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jComboBoxNewSalaryMonth.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jButtonNewSalaryClear.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNewSalaryClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNewSalaryClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finance/Broom-48.png"))); // NOI18N
        jButtonNewSalaryClear.setText("CLEAR");
        jButtonNewSalaryClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewSalaryClearActionPerformed(evt);
            }
        });

        jButtonNewSalaryAdd.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNewSalaryAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNewSalaryAdd.setForeground(new java.awt.Color(0, 0, 204));
        jButtonNewSalaryAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finance/addBlue.png"))); // NOI18N
        jButtonNewSalaryAdd.setText("ADD");
        jButtonNewSalaryAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewSalaryAddActionPerformed(evt);
            }
        });

        jDateChooserNewSalaryReceivedDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jDateChooserNewSalaryReceivedDate.setDateFormatString("yyyy-MM-dd");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Basic Salary Amount");

        JTextBoxNewSalaryBasicAmount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("OT Salary Amount");

        JTextBoxNewSalaryOTAmount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        JTextBoxNewSalaryHolderName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Salary Holder's Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(JTextBoxNewSalaryHolderName, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxNewSalaryMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(JTextBoxNewSalaryAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(JTextBoxNewSalaryOTAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(JTextBoxNewSalaryBasicAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserNewSalaryReceivedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNewSalaryClear, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonNewSalaryAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTextBoxNewSalaryHolderName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxNewSalaryMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTextBoxNewSalaryAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTextBoxNewSalaryBasicAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTextBoxNewSalaryOTAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserNewSalaryReceivedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewSalaryClear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewSalaryAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(156, 190, 234));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(619, 374));

        jTableNewSalary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableNewSalary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNewSalaryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableNewSalary);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Month");

        jComboBoxNewSalarySearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jButtonNewSalarySearch.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNewSalarySearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNewSalarySearch.setForeground(new java.awt.Color(255, 102, 0));
        jButtonNewSalarySearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finance/Search-48 (1).png"))); // NOI18N
        jButtonNewSalarySearch.setText("SEARCH");
        jButtonNewSalarySearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewSalarySearchActionPerformed(evt);
            }
        });

        jButtonNewSalaryRefresh.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNewSalaryRefresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNewSalaryRefresh.setForeground(new java.awt.Color(0, 153, 0));
        jButtonNewSalaryRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finance/Refresh-48 (1).png"))); // NOI18N
        jButtonNewSalaryRefresh.setText("REFRESH");
        jButtonNewSalaryRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewSalaryRefreshActionPerformed(evt);
            }
        });

        jButtonNewSalaryUpdate.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNewSalaryUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNewSalaryUpdate.setForeground(new java.awt.Color(255, 204, 0));
        jButtonNewSalaryUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finance/updateYelllow.png"))); // NOI18N
        jButtonNewSalaryUpdate.setText("UPDATE");
        jButtonNewSalaryUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewSalaryUpdateActionPerformed(evt);
            }
        });

        jButtonNewSalaryDelete.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNewSalaryDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNewSalaryDelete.setForeground(new java.awt.Color(255, 0, 0));
        jButtonNewSalaryDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/finance/deleteRed.png"))); // NOI18N
        jButtonNewSalaryDelete.setText("REMOVE");
        jButtonNewSalaryDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewSalaryDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxNewSalarySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonNewSalarySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNewSalaryRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonNewSalaryUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonNewSalaryDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewSalaryRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewSalarySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxNewSalarySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewSalaryDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewSalaryUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel58.setBackground(new java.awt.Color(204, 204, 204));
        jLabel58.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(102, 0, 102));
        jLabel58.setText("                      Add New Salary Details");
        jLabel58.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(102, 0, 102)));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 102));
        jLabel10.setText("                                                                          Salary Details");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(102, 0, 102)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewSalaryClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewSalaryClearActionPerformed

        JTextBoxNewSalaryAmount.setText("");
        ((JTextField)jDateChooserNewSalaryReceivedDate.getDateEditor().getUiComponent()).setText("");
        jComboBoxNewSalaryMonth.setSelectedItem("Select Month");
        JTextBoxNewSalaryHolderName.setText("");
        JTextBoxNewSalaryBasicAmount.setText("");
        JTextBoxNewSalaryOTAmount.setText("");

    }//GEN-LAST:event_jButtonNewSalaryClearActionPerformed

    private void jButtonNewSalaryAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewSalaryAddActionPerformed

        try{
            String salaryHolderName;     //salary holder's name           
            String month;                //salary received month   
            String salaryAmount;         //salary amount
            String basicSalary;          //basic salary
            String otSalary;             //OT salary payment
            Date salaryReceivedDate;     //salary received date

            salaryHolderName = JTextBoxNewSalaryHolderName.getText();
            month = jComboBoxNewSalaryMonth.getSelectedItem().toString();
            salaryAmount = JTextBoxNewSalaryAmount.getText();            
            basicSalary = JTextBoxNewSalaryBasicAmount.getText();
            otSalary = JTextBoxNewSalaryOTAmount.getText();
            salaryReceivedDate = jDateChooserNewSalaryReceivedDate.getDate();

            Salary newsalary = new Salary();
            newsalary.setSalaryHolderName(salaryHolderName);
            newsalary.setMonth(month);
            newsalary.setSalaryAmount(salaryAmount);
            newsalary.setBasicSalary(basicSalary);
            newsalary.setOtsalary(otSalary);
            newsalary.setSalaryReceivedDate(salaryReceivedDate);

            SalaryController.addSalary(newsalary);
        }

        catch(Exception e){

            JOptionPane.showMessageDialog(null, e);
        }
             
        displaytable();
        
        JTextBoxNewSalaryAmount.setText("");
        ((JTextField)jDateChooserNewSalaryReceivedDate.getDateEditor().getUiComponent()).setText("");
        jComboBoxNewSalaryMonth.setSelectedItem("Select Month");
        JTextBoxNewSalaryHolderName.setText("");
        JTextBoxNewSalaryBasicAmount.setText("");
        JTextBoxNewSalaryOTAmount.setText("");
    }//GEN-LAST:event_jButtonNewSalaryAddActionPerformed

    private void jTableNewSalaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNewSalaryMouseClicked

        int i = jTableNewSalary.getSelectedRow();

        JTextBoxNewSalaryHolderName.setText(jTableNewSalary.getValueAt(i, 1).toString());
        jComboBoxNewSalaryMonth.setSelectedItem(jTableNewSalary.getValueAt(i, 2).toString());
        JTextBoxNewSalaryAmount.setText(jTableNewSalary.getValueAt(i, 3).toString());        
        JTextBoxNewSalaryBasicAmount.setText(jTableNewSalary.getValueAt(i, 4).toString());
        JTextBoxNewSalaryOTAmount.setText(jTableNewSalary.getValueAt(i, 5).toString());
        ((JTextField)jDateChooserNewSalaryReceivedDate .getDateEditor().getUiComponent()).setText(jTableNewSalary.getValueAt(i, 6).toString());
    }//GEN-LAST:event_jTableNewSalaryMouseClicked

    private void jButtonNewSalarySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewSalarySearchActionPerformed
        displaySearch();
    }//GEN-LAST:event_jButtonNewSalarySearchActionPerformed

    private void jButtonNewSalaryRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewSalaryRefreshActionPerformed
        displaytable();
    }//GEN-LAST:event_jButtonNewSalaryRefreshActionPerformed

    private void jButtonNewSalaryUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewSalaryUpdateActionPerformed

            int response = JOptionPane.showConfirmDialog(null, "Do you really want to update?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (response == JOptionPane.YES_OPTION) {

            int i = jTableNewSalary.getSelectedRow();
            String ID = jTableNewSalary.getValueAt(i, 0).toString();

            String salaryHolderName;     //salary holder's name           
            String month;                //salary received month   
            String salaryAmount;         //salary amount
            String basicSalary;          //basic salary
            String otSalary;             //OT salary payment
            Date salaryReceivedDate;     //salary received date

            salaryHolderName = JTextBoxNewSalaryHolderName.getText();
            month = jComboBoxNewSalaryMonth.getSelectedItem().toString();
            salaryAmount = JTextBoxNewSalaryAmount.getText();            
            basicSalary = JTextBoxNewSalaryBasicAmount.getText();
            otSalary = JTextBoxNewSalaryOTAmount.getText();
            salaryReceivedDate = jDateChooserNewSalaryReceivedDate.getDate();
          
            if(salaryHolderName.equals(jTableNewSalary.getValueAt(i, 1).toString()))
            {   
                Salary newsalary = new Salary();
                newsalary.setSalaryId(Integer.parseInt(ID));
                newsalary.setSalaryHolderName(salaryHolderName);
                newsalary.setMonth(month);
                newsalary.setSalaryAmount(salaryAmount);
                newsalary.setBasicSalary(basicSalary);
                newsalary.setOtsalary(otSalary);
                newsalary.setSalaryReceivedDate(salaryReceivedDate);

                SalaryController.updateSalary(newsalary);

                displaytable();
            }
            
            else 
            {
                JOptionPane.showMessageDialog(null, "Salary Holder's Name cannot be edited!! Please try to edit other details without name!");
            }

        }
    }//GEN-LAST:event_jButtonNewSalaryUpdateActionPerformed

    private void jButtonNewSalaryDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewSalaryDeleteActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Do you really want to delete?", "Confirm",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {

            int i = jTableNewSalary.getSelectedRow();
            SalaryController.DeleteSalary(jTableNewSalary.getValueAt(i, 0).toString());
            displaytable();

        }
    }//GEN-LAST:event_jButtonNewSalaryDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextBoxNewSalaryAmount;
    private javax.swing.JTextField JTextBoxNewSalaryBasicAmount;
    private javax.swing.JTextField JTextBoxNewSalaryHolderName;
    private javax.swing.JTextField JTextBoxNewSalaryOTAmount;
    private javax.swing.JButton jButtonNewSalaryAdd;
    private javax.swing.JButton jButtonNewSalaryClear;
    private javax.swing.JButton jButtonNewSalaryDelete;
    private javax.swing.JButton jButtonNewSalaryRefresh;
    private javax.swing.JButton jButtonNewSalarySearch;
    private javax.swing.JButton jButtonNewSalaryUpdate;
    private javax.swing.JComboBox jComboBoxNewSalaryMonth;
    private static javax.swing.JComboBox jComboBoxNewSalarySearch;
    private com.toedter.calendar.JDateChooser jDateChooserNewSalaryReceivedDate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTableNewSalary;
    // End of variables declaration//GEN-END:variables
}
