package model.plan;
// Generated May 1, 2016 3:39:36 PM by Hibernate Tools 4.3.1

import javax.validation.constraints.Pattern;
import org.hibernate.validator.constraints.NotEmpty;




/**
 * Homeplan generated by hbm2java
 */
public class Homeplan  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String address;
     private String contact1;
     private String contact2;
     private String owner;

    public Homeplan() {
    }

    public Homeplan(String name, String address, String contact1, String contact2, String owner) {
       this.name = name;
       this.address = address;
       this.contact1 = contact1;
       this.contact2 = contact2;
       this.owner = owner;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @NotEmpty
    public String getName() {
        return this.name;
    }
    
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Pattern(regexp="(^$|[0-9]{10})",message = "Invaild Contact Number")
    public String getContact1() {
        return this.contact1;
    }
    
    public void setContact1(String contact1) {
        this.contact1 = contact1;
    }
    
    @Pattern(regexp="(^$|[0-9]{10})",message = "Invaild Contact Number")
    public String getContact2() {
        return this.contact2;
    }
    
    public void setContact2(String contact2) {
        this.contact2 = contact2;
    }
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }




}


