    package model.room;
// Generated May 1, 2016 3:39:36 PM by Hibernate Tools 4.3.1

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;




/**
 * Homerooms generated by hbm2java
 */
public class Homerooms  implements java.io.Serializable {


     private Integer id;
     private String type;
     private String name;
     private String owner;
     private int floor;
     private String contact;
     private String location;

    public Homerooms() {
    }

    public Homerooms(String type, String name, String owner, int floor, String contact, String location) {
       this.type = type;
       this.name = name;
       this.owner = owner;
       this.floor = floor;
       this.contact = contact;
       this.location = location;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @NotNull
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    
    @NotNull
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @NotNull
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }
    
    //@Pattern(regexp = "[0-9]+",message = "Invaild Floor")
    public int getFloor() {
        return this.floor;
    }
    
    
    public void setFloor(int floor) {
        this.floor = floor;
    }
    
    //@Pattern(regexp="(^$|[0-9]{10})",message = "Invaild Contact Number")
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }




}


