/*
 * Copyright (c) 2016 SLIIT, All Rights Reserved.
 * HOME MANAGEMENT SYSTEM
 * SEP GROUP PROJECT - 3rd YEAR
 *
 */
package view.user;

import controllers.user.UserContactController;
import java.util.Date;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * SearchContacts -- Interface for search contacts
 * @author Nimanthika
 * 
 */
public class SearchContacts extends javax.swing.JInternalFrame {

    /**
     * Creates new form SearchContacts
     */
    public SearchContacts() {
        initComponents();
        
        //Hide menu bar of the SearchContacts jInternalFrame
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        //Load SearchContactTable when the form is loading
        displaySearchedContactTable();
    }

     /**
     * Method to load SearchContactTable when user searching a contact
     */   
      public static void displaySearchedContactTable(){

          //Get user entered values
          String name = NameTextField.getText();
          String group = ComboBoxGroup.getSelectedItem().toString();
          
          //If user didn't select a group from the group combo box.
          if(group.equals("Select the group")){
              
              SearchContactTable.setModel(UserContactController.displaySearchedContactTableWithoutGroup(name));
              HideColumns();
          }
        
          //If user selects a group from the group combo box.
          else{
              
              SearchContactTable.setModel(UserContactController.displaySearchedContactTableWithGroup(name, group));  
              HideColumns();
          }
      }
          
      /**
     * Method to load SearchContactTable when user selects a group in the combo box
     */
      public static void displayContactByGroup(){
          
          String group = ComboBoxGroup.getSelectedItem().toString();
        
          //If user didn't select a group from the group combo box.
          if(group.equals("Select the group")){    
              
              displaySearchedContactTable();      
          }
             
          //If user selects a group from the group combo box.
          else{
              
              SearchContactTable.setModel(UserContactController.displaySearchedContactTableByGroup(group)); 
              HideColumns();
          }
      }
          
      /**
     * Method to fill the form when user clicks on a row of SearchContactTable
     */
      public static void FillForm(){    		
        
        int r = SearchContactTable.getSelectedRow();
        
        TextBoxName.setText(SearchContactTable.getValueAt(r, 0).toString());
        TextBoxMobile1.setText(SearchContactTable.getValueAt(r, 1).toString());
        TextBoxTelephone1.setText(SearchContactTable.getValueAt(r, 2).toString());   
        TextBoxCompanyName.setText(SearchContactTable.getValueAt(r, 5).toString());
        DateChooserDOB.setDate((Date)SearchContactTable.getValueAt(r, 6));
        TextBoxTelephone2.setText(SearchContactTable.getValueAt(r, 7).toString());
        TextBoxMobile2.setText(SearchContactTable.getValueAt(r, 8).toString());
        TextBoxEmail1.setText(SearchContactTable.getValueAt(r, 9).toString());
        TextBoxEmail2.setText(SearchContactTable.getValueAt(r, 10).toString());
        TextAreaAddress.setText(SearchContactTable.getValueAt(r, 11).toString());  
    }
    
      /**
     * Method to clear the form
     */
    public void FormClear(){
        
        TextBoxName.setText(null);
        TextBoxCompanyName.setText(null);
        DateChooserDOB.setDate(null);
        TextBoxTelephone1.setText(null);
        TextBoxTelephone2.setText(null);
        TextBoxMobile1.setText(null);
        TextBoxMobile2.setText(null);
        TextBoxEmail1.setText(null);
        TextBoxEmail2.setText(null);
        TextAreaAddress.setText(null);
    }
    
    /**
     * Method to hide unwanted columns of the table
     */
    public static void HideColumns(){
        
        //hide columns(3-11) in table 
        for(int i=3; i<=11; i++){
        
            SearchContactTable.getColumnModel().getColumn(i).setWidth(0);
            SearchContactTable.getColumnModel().getColumn(i).setMinWidth(0);
            SearchContactTable.getColumnModel().getColumn(i).setMaxWidth(0);
        }   
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        SearchContactTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        TextBoxName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TextBoxCompanyName = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        TextBoxTelephone1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TextBoxTelephone2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        TextBoxMobile1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        TextBoxMobile2 = new javax.swing.JTextField();
        TextBoxEmail2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TextBoxEmail1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaAddress = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        DateChooserDOB = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        ClearButton = new javax.swing.JButton();
        ClearFormButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        ComboBoxGroup = new javax.swing.JComboBox();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1370, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(156, 190, 234));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 3), "Search Contacts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel6.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Name");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 40, 30));

        NameTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(156, 190, 234), 2));
        NameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NameTextFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NameTextFieldKeyReleased(evt);
            }
        });
        jPanel6.add(NameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 150, 30));

        SearchContactTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SearchContactTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Mobile No.1", "Telephone No.1"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SearchContactTable.setGridColor(new java.awt.Color(255, 255, 255));
        SearchContactTable.setRowHeight(35);
        SearchContactTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchContactTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(SearchContactTable);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 410, 360));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Name");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 70, 20));

        TextBoxName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextBoxName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(156, 190, 234), 2));
        jPanel6.add(TextBoxName, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 210, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Company Name");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 120, 20));

        TextBoxCompanyName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextBoxCompanyName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(156, 190, 234), 2));
        jPanel6.add(TextBoxCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 210, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Telephone No.1");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 110, 20));

        TextBoxTelephone1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextBoxTelephone1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(156, 190, 234), 2));
        jPanel6.add(TextBoxTelephone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 210, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Telephone No.2");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, -1, 20));

        TextBoxTelephone2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextBoxTelephone2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(156, 190, 234), 2));
        jPanel6.add(TextBoxTelephone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 210, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Mobile No.1");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 90, 20));

        TextBoxMobile1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextBoxMobile1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(156, 190, 234), 2));
        jPanel6.add(TextBoxMobile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 210, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Mobile No.2");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 100, 20));

        TextBoxMobile2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextBoxMobile2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(156, 190, 234), 2));
        TextBoxMobile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBoxMobile2ActionPerformed(evt);
            }
        });
        jPanel6.add(TextBoxMobile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 210, 30));

        TextBoxEmail2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextBoxEmail2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(156, 190, 234), 2));
        jPanel6.add(TextBoxEmail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 400, 210, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Email 2");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 380, 60, 20));

        TextBoxEmail1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextBoxEmail1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(156, 190, 234), 2));
        jPanel6.add(TextBoxEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 340, 210, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Email 1");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 320, 90, 20));

        TextAreaAddress.setColumns(20);
        TextAreaAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TextAreaAddress.setRows(5);
        TextAreaAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(156, 190, 234), 2));
        jScrollPane2.setViewportView(TextAreaAddress);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 160, 210, 140));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Address");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 140, -1, 20));

        DateChooserDOB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(156, 190, 234), 2));
        DateChooserDOB.setDateFormatString("dd-MM-yyyy");
        DateChooserDOB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel6.add(DateChooserDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 100, 210, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Date Of Birth");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 80, 90, 20));

        ClearButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(156, 190, 234), 2));
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });
        jPanel6.add(ClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 70, 30));

        ClearFormButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ClearFormButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User/Clear.png"))); // NOI18N
        ClearFormButton.setText("Clear");
        ClearFormButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(156, 190, 234), 2));
        ClearFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearFormButtonActionPerformed(evt);
            }
        });
        jPanel6.add(ClearFormButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 460, 140, 50));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Group");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 70, 30));

        ComboBoxGroup.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ComboBoxGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select the group", "Family", "Office", "Friends", "Emergency", "Doctors" }));
        ComboBoxGroup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(156, 190, 234), 2));
        ComboBoxGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxGroupActionPerformed(evt);
            }
        });
        jPanel6.add(ComboBoxGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 150, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 1200, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameTextFieldKeyReleased

        //Search contacts while user typing in textbox
        displaySearchedContactTable();  
    }//GEN-LAST:event_NameTextFieldKeyReleased

    private void NameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldKeyPressed

    private void SearchContactTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchContactTableMouseClicked
        
        //Call the FillForm method when user clicks on a row of SearchContactTable
        FillForm();
    }//GEN-LAST:event_SearchContactTableMouseClicked

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed

        //Clear name textbox
        NameTextField.setText(null);  
        
        //set group combobox to default value 
        ComboBoxGroup.setSelectedIndex(0); 
        
        //Refresh the table
        displaySearchedContactTable();
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void ClearFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearFormButtonActionPerformed

        //Clear name textbox
        NameTextField.setText(null); 
        
        //set group combobox to default value 
        ComboBoxGroup.setSelectedIndex(0); 
        
        //Call FormClear method to clear the form
        FormClear();
        
        //Refresh the table
        displaySearchedContactTable();
        
    }//GEN-LAST:event_ClearFormButtonActionPerformed

    private void ComboBoxGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxGroupActionPerformed

         //Call displayContactByGroup method when user selects a group from combo box
        displayContactByGroup();
    }//GEN-LAST:event_ComboBoxGroupActionPerformed

    private void TextBoxMobile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBoxMobile2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBoxMobile2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton ClearFormButton;
    private static javax.swing.JComboBox ComboBoxGroup;
    private static com.toedter.calendar.JDateChooser DateChooserDOB;
    private static javax.swing.JTextField NameTextField;
    private static javax.swing.JTable SearchContactTable;
    private static javax.swing.JTextArea TextAreaAddress;
    private static javax.swing.JTextField TextBoxCompanyName;
    private static javax.swing.JTextField TextBoxEmail1;
    private static javax.swing.JTextField TextBoxEmail2;
    private static javax.swing.JTextField TextBoxMobile1;
    private static javax.swing.JTextField TextBoxMobile2;
    private static javax.swing.JTextField TextBoxName;
    private static javax.swing.JTextField TextBoxTelephone1;
    private static javax.swing.JTextField TextBoxTelephone2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
