package model.food;
// Generated May 1, 2016 3:39:36 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.validation.constraints.Future;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Homefood generated by hbm2java
 */
public class Homefood  implements java.io.Serializable {


     private Integer foodId;
     private String catagory;
     private String description;
     private int quantity;
     private String measurment;
     private String price;
     private Date date;
     private String address;
     private String contact;

    public Homefood() {
    }

    public Homefood(String catagory, String description, int quantity, String measurment, String price, Date date, String address, String contact) {
       this.catagory = catagory;
       this.description = description;
       this.quantity = quantity;
       this.measurment = measurment;
       this.price = price;
       this.date = date;
       this.address = address;
       this.contact = contact;
    }
   
    public Integer getFoodId() {
        return this.foodId;
    }
    
    public void setFoodId(Integer foodId) {
        this.foodId = foodId;
    }
    
    
    public String getCatagory() {
        return this.catagory;
    }
    
    public void setCatagory(String catagory) {
        this.catagory = catagory;
    }
    
    @NotEmpty
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    
    
    public String getMeasurment() {
        return this.measurment;
    }
    
    public void setMeasurment(String measurment) {
        this.measurment = measurment;
    }
    
    @Pattern(regexp = "[0-9]+",message = "Invaild Price")
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    
    @NotNull
    @Future(message="Invalid Date")
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    @Pattern(regexp="(^$|[0-9]{10})",message = "Invaild Contact Number")
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }




}


