package model.event;
// Generated May 1, 2016 3:39:36 PM by Hibernate Tools 4.3.1



/**
 * Eventfood generated by hbm2java
 */
public class Eventfood  implements java.io.Serializable {


     private Integer id;
     private String menuName;
     private String itemName;
     private String price;

    public Eventfood() {
    }

	
    public Eventfood(String menuName) {
        this.menuName = menuName;
    }
    public Eventfood(String menuName, String itemName, String price) {
       this.menuName = menuName;
       this.itemName = itemName;
       this.price = price;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMenuName() {
        return this.menuName;
    }
    
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }




}


