package model.event;
// Generated May 1, 2016 3:39:36 PM by Hibernate Tools 4.3.1



/**
 * Eventnbev generated by hbm2java
 */
public class Eventnbev  implements java.io.Serializable {


     private Integer id;
     private String name;
     private int quantity;
     private int eventId;

    public Eventnbev() {
    }

    public Eventnbev(String name, int quantity, int eventId) {
       this.name = name;
       this.quantity = quantity;
       this.eventId = eventId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public int getEventId() {
        return this.eventId;
    }
    
    public void setEventId(int eventId) {
        this.eventId = eventId;
    }




}


