package model.event;
// Generated May 1, 2016 3:39:36 PM by Hibernate Tools 4.3.1



/**
 * Eventncontact generated by hbm2java
 */
public class Eventncontact  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String address;
     private int eventId;

    public Eventncontact() {
    }

    public Eventncontact(String name, String address, int eventId) {
       this.name = name;
       this.address = address;
       this.eventId = eventId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public int getEventId() {
        return this.eventId;
    }
    
    public void setEventId(int eventId) {
        this.eventId = eventId;
    }




}


