/*
 * Copyright (c) 2016 SLIIT, All Rights Reserved.
 * HOME MANAGEMENT SYSTEM
 * SEP GROUP PROJECT - 3rd YEAR
 *
 */
package view.plan;

import controller.plan.PlanController;
import controller.room.RoomController;
import java.awt.Color;
import java.util.List;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.plan.Homeplan;
import model.room.Homerooms;

/**
 * HomePlanDetails -- main Interface for Home Plan 
 * @author Isurunath
 */
public class HomePlanDetails extends javax.swing.JInternalFrame {
    
    static int updateID;    //Store Event ID for updtaing event
    
    public HomePlanDetails() {
        initComponents();
        
        //remove frame of Internal Frame
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        //Change color of side bar panel
        PlanFrame.jPanel7.setBackground(new Color (156,190,234));
        PlanFrame.jPanel9.setBackground(new Color (102,0,102));
        
        load();
        displaytable();
    }
    
    public static void displaytable(){
    	
    	jTable2.setModel(RoomController.displayRoomTable());
        
        //hide ID column in table
        jTable2.getColumnModel().getColumn(0).setWidth(0);
        jTable2.getColumnModel().getColumn(0).setMinWidth(0);
        jTable2.getColumnModel().getColumn(0).setMaxWidth(0);
    }
    
    public static void load(){
        
        List l = PlanController.loadPlan();
        for(Object o:l){
            
            Homeplan items = (Homeplan)o;
            updateID = items.getId();
            name.setText(items.getName());
            address.setText(items.getAddress());
            contact1.setText(items.getContact1());
            contact2.setText(items.getContact2());
            owner.setText(items.getOwner());
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        contact1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        owner = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        contact2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rcontact = new javax.swing.JTextField();
        rtype = new javax.swing.JTextField();
        rname = new javax.swing.JTextField();
        rowner = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        rlocation = new javax.swing.JTextField();
        rfloor = new javax.swing.JSpinner();

        setBackground(java.awt.Color.white);
        setBorder(null);
        setForeground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(1280, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Add Participants");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, -110, -1, -1));

        jLabel8.setText("Foods & drinks");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, -110, -1, -1));

        jPanel1.setBackground(new java.awt.Color(156, 190, 234));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setBackground(new java.awt.Color(254, 254, 254));
        name.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(1, 1, 1));
        name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(70, 105, 151), 2, true));
        name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        name.setSelectionColor(new java.awt.Color(62, 155, 208));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 290, 40));

        jLabel12.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(70, 105, 151));
        jLabel12.setText("Home Name");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(70, 105, 151));
        jLabel13.setText("Home Contact 1");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        contact1.setBackground(new java.awt.Color(254, 254, 254));
        contact1.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        contact1.setForeground(new java.awt.Color(1, 1, 1));
        contact1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        contact1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(70, 105, 151), 2, true));
        contact1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        contact1.setSelectionColor(new java.awt.Color(62, 155, 208));
        contact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact1ActionPerformed(evt);
            }
        });
        jPanel1.add(contact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 290, 40));

        jLabel14.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(70, 105, 151));
        jLabel14.setText("Owner");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        owner.setBackground(new java.awt.Color(254, 254, 254));
        owner.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        owner.setForeground(new java.awt.Color(1, 1, 1));
        owner.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        owner.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(70, 105, 151), 2, true));
        owner.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        owner.setSelectionColor(new java.awt.Color(62, 155, 208));
        owner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerActionPerformed(evt);
            }
        });
        jPanel1.add(owner, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 290, 40));

        jLabel15.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(70, 105, 151));
        jLabel15.setText("Address");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        address.setBackground(new java.awt.Color(254, 254, 254));
        address.setColumns(20);
        address.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        address.setForeground(new java.awt.Color(1, 1, 1));
        address.setRows(5);
        address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(70, 105, 151)));
        jScrollPane2.setViewportView(address);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 290, -1));

        contact2.setBackground(new java.awt.Color(254, 254, 254));
        contact2.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        contact2.setForeground(new java.awt.Color(1, 1, 1));
        contact2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        contact2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(70, 105, 151), 2, true));
        contact2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        contact2.setSelectionColor(new java.awt.Color(62, 155, 208));
        contact2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact2ActionPerformed(evt);
            }
        });
        jPanel1.add(contact2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 290, 40));

        jLabel16.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(70, 105, 151));
        jLabel16.setText("Home Contact 2");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 204, 51));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\updateYelllow.png")); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 290, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 600));

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(92, 126, 150));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Room List"));
        jPanel3.setForeground(new java.awt.Color(92, 126, 150));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Type", "Room Name", "Owner"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 720, 190));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 850, 270));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Room Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Type");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Owner");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Floor");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Contact");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));
        jPanel2.add(rcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 200, 30));
        jPanel2.add(rtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 200, 30));
        jPanel2.add(rname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 200, 30));
        jPanel2.add(rowner, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 200, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 153, 51));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\updateYelllow.png")); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 140, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 255));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\addBlue.png")); // NOI18N
        jButton3.setText("ADD ROOM");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 140, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 51));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isurunath\\Documents\\NetBeansProjects\\Home\\Lib\\images\\deleteRed.png")); // NOI18N
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 140, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("location");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, -1, -1));
        jPanel2.add(rlocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 200, 30));
        jPanel2.add(rfloor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 200, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 920, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void contact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contact1ActionPerformed

    private void ownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownerActionPerformed

    private void contact2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contact2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String Name;
        String Adddress;
        String Contact1;
        String Contact2;
        String Owner;

        Name = name.getText();
        Adddress = address.getText();
        Contact1 = contact1.getText();
        Contact2 = contact2.getText();
        Owner = owner.getText();

        Homeplan plan = new Homeplan();
        plan.setId(updateID);
        plan.setName(Name);
        plan.setAddress(Adddress);
        plan.setContact1(Contact1);
        plan.setContact2(Contact2);
        plan.setOwner(Owner);

        PlanController.updateEvent(plan);
        load();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String type;
        String name;
        String owner;
        int floor;
        String contact;
        String location;
        
        type = rtype.getText();
        name = rname.getText();
        owner = rowner.getText();
        floor = Integer.parseInt(rfloor.getSize().toString());
        contact = rcontact.getText();
        location = rlocation.getText();
        
        Homerooms r = new Homerooms();
        r.setName(name);
        r.setType(type);
        r.setOwner(owner);
        r.setFloor(floor);
        r.setContact(contact);
        r.setLocation(location);
        
        RoomController.AddRoom(r);
        displaytable();


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int i = jTable2.getSelectedRow();
        rtype.setText(jTable2.getValueAt(i, 1).toString());
        rname.setText(jTable2.getValueAt(i, 2).toString());
        rowner.setText(jTable2.getValueAt(i, 3).toString());
        rfloor.setValue(jTable2.getValueAt(i, 4).toString());
        rcontact.setText(jTable2.getValueAt(i, 5).toString());
        rlocation.setText(jTable2.getValueAt(i, 6).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        int i = jTable2.getSelectedRow();
        int id = Integer.parseInt(jTable2.getValueAt(i, 0).toString());
        
        String type;
        String name;
        String owner;
        int floor;
        String contact;
        String location;
        
        type = rtype.getText();
        name = rname.getText();
        owner = rowner.getText();
        floor = Integer.parseInt(rfloor.getSize().toString());
        contact = rcontact.getText();
        location = rlocation.getText();
        
        Homerooms r = new Homerooms();
        r.setId(id);
        r.setName(name);
        r.setType(type);
        r.setOwner(owner);
        r.setFloor(floor);
        r.setContact(contact);
        r.setLocation(location);
        
        RoomController.updateRoom(r);
        displaytable();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int i = jTable2.getSelectedRow();
        String id = jTable2.getValueAt(i, 0).toString();
        RoomController.DeleteRoom(id);
        displaytable();
    }//GEN-LAST:event_jButton4ActionPerformed
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextArea address;
    public static javax.swing.JTextField contact1;
    public static javax.swing.JTextField contact2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JTable jTable2;
    public static javax.swing.JTextField name;
    public static javax.swing.JTextField owner;
    private javax.swing.JTextField rcontact;
    private javax.swing.JSpinner rfloor;
    private javax.swing.JTextField rlocation;
    private javax.swing.JTextField rname;
    private javax.swing.JTextField rowner;
    private javax.swing.JTextField rtype;
    // End of variables declaration//GEN-END:variables
}
